<?php

return array (
  0 => 
  array (
    'id' => 1,
    'category_id' => 1,
    'order_number' => 1,
    'full_number' => '1.1',
    'title' => 'Ketergantungan Impor dan Krisis Produksi Pangan Domestik',
    'description' => 'Produksi pangan nasional belum mampu sepenuhnya memenuhi kebutuhan dalam negeri, sehingga impor masih menjadi penopang utama stabilitas harga dan ketersediaan komoditas strategis. Struktur usaha tani yang didominasi skala kecil, praktik budidaya manual, serta keterbatasan mekanisasi membuat produktivitas lahan dan tenaga kerja rendah. Akses petani terhadap alat dan mesin modern, pelatihan teknis, pembiayaan, dan asuransi pertanian masih terbatas, sehingga sulit melakukan intensifikasi dan efisiensi biaya produksi. Diversifikasi sumber pangan lokal, termasuk pangan non-beras dan komoditas asli Indonesia, belum mendapatkan dukungan riset dan kebijakan yang memadai. Tanpa transformasi sistem produksi domestik, ketergantungan pada pangan impor akan terus berlanjut dan mengancam keberlanjutan program seperti Pangan Bergizi Gratis yang idealnya berbasis pada komoditas pangan nasional.',
    'created_at' => '2025-12-07 20:20:13',
    'updated_at' => '2025-12-07 20:20:13',
  ),
  1 => 
  array (
    'id' => 2,
    'category_id' => 1,
    'order_number' => 2,
    'full_number' => '1.2',
    'title' => 'Lambatnya Adopsi Teknologi dan Transformasi Digital dalam Ekosistem Pangan',
    'description' => 'Digitalisasi sektor pangan di Indonesia belum berjalan menyeluruh dan merata, terutama pada petani kecil dan pelaku UMKM pangan. Banyak pelaku masih mengandalkan praktik tradisional dalam pencatatan produksi, distribusi, dan pemasaran, sehingga sulit mengakses informasi harga, cuaca, permintaan pasar, dan pembiayaan. Pemanfaatan teknologi Internet of Things (IoT), sensor lapangan, dan blockchain untuk pencatatan rantai pasok, pelacakan keamanan pangan, serta transparansi transaksi masih sangat terbatas. Hambatan utama berupa biaya investasi awal, rendahnya literasi digital, dan belum adanya kebijakan adopsi teknologi yang berpihak pada pelaku kecil. Tanpa riset terapan dan model bisnis Smart Farming yang mudah direplikasi, transformasi digital di sektor pangan akan berjalan lambat dan meninggalkan kesenjangan antara wilayah maju dan tertinggal.',
    'created_at' => '2025-12-07 20:20:34',
    'updated_at' => '2025-12-07 20:20:34',
  ),
  2 => 
  array (
    'id' => 3,
    'category_id' => 1,
    'order_number' => 3,
    'full_number' => '1.3',
    'title' => 'Dampak Perubahan Iklim Dan Rendahnya Adopsi Pertanian Berkelanjutan',
    'description' => 'Perubahan iklim semakin memicu ketidakpastian produksi pangan melalui pergeseran pola hujan, kekeringan berkepanjangan, banjir, serta serangan organisme pengganggu tanaman. Riset adaptasi iklim di sektor pangan umumnya masih parsial, terfragmentasi, dan belum sepenuhnya terintegrasi ke dalam kebijakan nasional maupun perencanaan daerah. Sebagian besar petani masih menerapkan praktik pertanian konvensional yang mengandalkan input kimia tinggi, pengolahan tanah intensif, dan monokultur, yang berkontribusi pada degradasi tanah, penurunan keanekaragaman hayati, dan peningkatan emisi gas rumah kaca. Insentif dan skema pembiayaan untuk praktik pertanian regeneratif, agroforestry, dan low-emission agriculture masih minim. Tanpa percepatan adopsi pertanian berkelanjutan secara sistemik, ketahanan pangan nasional akan semakin rentan terhadap guncangan iklim.',
    'created_at' => '2025-12-07 20:20:56',
    'updated_at' => '2025-12-07 20:20:56',
  ),
  3 => 
  array (
    'id' => 4,
    'category_id' => 1,
    'order_number' => 4,
    'full_number' => '1.4',
    'title' => 'Terbatasnya Riset dan Komersialisasi Pangan Fungsional Lokal',
    'description' => 'Potensi sumber daya hayati Indonesia sebagai basis pengembangan pangan fungsional dan bioteknologi pangan masih jauh dari optimal. Banyak komoditas lokal yang kaya senyawa bioaktif dan berkhasiat kesehatan belum diolah menjadi produk bernilai tambah tinggi yang mampu bersaing di pasar domestik dan global. Riset lanjutan mengenai klaim kesehatan, stabilitas produk, formulasi, dan keamanan pangan masih terbatas, sementara proses perizinan dan regulasi sering kali kompleks serta memakan waktu. Keterbatasan fasilitas pilot plant, kemitraan industri, dan pendanaan tahap hilirisasi menghambat komersialisasi inovasi dari kampus dan lembaga riset. Tanpa ekosistem yang mendukung dari riset hingga pasar, peluang menjadikan pangan fungsional lokal sebagai keunggulan kompetitif Indonesia akan terlewat.',
    'created_at' => '2025-12-07 20:21:17',
    'updated_at' => '2025-12-07 20:21:17',
  ),
  4 => 
  array (
    'id' => 5,
    'category_id' => 1,
    'order_number' => 5,
    'full_number' => '1.5',
    'title' => 'Lemahnya Sistem Swasembada Benih Nasional',
    'description' => 'Swasembada benih untuk komoditas strategis seperti padi, jagung, kedelai, dan hortikultura belum tercapai karena kapasitas riset pemuliaan dan kelembagaan perbenihan domestik masih terbatas. Fasilitas pemuliaan, kebun plasma nutfah, laboratorium, dan lahan uji adaptasi belum cukup untuk menghasilkan varietas unggul yang adaptif terhadap perubahan iklim dan preferensi pasar. Proses sertifikasi benih, perlindungan varietas lokal, serta sistem distribusi benih bermutu ke petani kecil belum berjalan optimal. Ketergantungan pada varietas impor dan benih perusahaan besar mengurangi kemandirian petani dan mengancam keberlanjutan sumber daya genetik lokal. Tanpa penguatan ekosistem benih nasional dari hulu ke hilir, ketahanan produksi pangan Indonesia akan tetap rapuh di tengah dinamika iklim dan pasar global.',
    'created_at' => '2025-12-07 20:21:31',
    'updated_at' => '2025-12-07 20:21:31',
  ),
  5 => 
  array (
    'id' => 6,
    'category_id' => 1,
    'order_number' => 6,
    'full_number' => '1.6',
    'title' => 'Kerentanan Sistem Distribusi dan Logistik Pangan serta Tingginya Food Loss dan Food Waste',
    'description' => 'Sistem distribusi dan logistik pangan nasional masih menghadapi kendala infrastruktur, khususnya di wilayah terpencil, kepulauan, dan daerah dengan akses jalan terbatas. Jaringan rantai dingin untuk produk segar dan mudah rusak belum merata, sehingga banyak komoditas mengalami penurunan mutu atau membusuk sebelum sampai konsumen. Digitalisasi logistik dan integrasi data pasokan–permintaan belum berkembang luas, menyebabkan mismatch distribusi dan fluktuasi harga tajam antar wilayah. Di sepanjang rantai nilai, praktik penyimpanan kurang memadai, standar penanganan pascapanen lemah, dan perilaku konsumsi cenderung boros, sehingga food loss dan food waste tetap tinggi. Kondisi ini tidak hanya menurunkan efisiensi sistem pangan, tetapi juga berdampak pada emisi, kerugian ekonomi, dan ketidakadilan akses pangan.',
    'created_at' => '2025-12-07 20:21:48',
    'updated_at' => '2025-12-07 20:21:48',
  ),
  6 => 
  array (
    'id' => 7,
    'category_id' => 1,
    'order_number' => 7,
    'full_number' => '1.7',
    'title' => 'Minimnya Insentif untuk Riset Pangan yang Berorientasi Pasar dan Keberlanjutan',
    'description' => 'Sebagian besar riset pangan di Indonesia masih berfokus pada aspek teknis di laboratorium tanpa strategi jelas untuk memasuki pasar dan memperbaiki dampak lingkungan. Keterlibatan pelaku industri, pelaku usaha tani, dan konsumen dalam perumusan agenda riset masih terbatas, sehingga banyak inovasi tidak menjawab kebutuhan riil rantai pasok pangan. Skema pendanaan belum secara eksplisit mendorong riset lintas disiplin yang menggabungkan aspek teknologi, model bisnis, dan keberlanjutan ekologi. Dukungan untuk tahap hilirisasi, pengujian pasar, dan pengembangan merek juga minim. Tanpa insentif dan kerangka penilaian yang mengutamakan dampak pasar dan lingkungan, jarak antara hasil riset dan implementasi komersial yang signifikan akan terus melebar.',
    'created_at' => '2025-12-07 20:23:01',
    'updated_at' => '2025-12-07 20:23:01',
  ),
  7 => 
  array (
    'id' => 8,
    'category_id' => 1,
    'order_number' => 8,
    'full_number' => '1.8',
    'title' => 'Rendahnya Literasi Pangan Sehat dan Perilaku Konsumsi Bergizi Seimbang',
    'description' => 'Masyarakat Indonesia masih menghadapi tantangan serius dalam menerapkan pola makan bergizi seimbang, beragam, dan berkelanjutan. Tingginya konsumsi gula, garam, dan lemak, serta rendahnya konsumsi buah, sayur, dan sumber protein berkualitas berkontribusi pada beban ganda malnutrisi: kekurangan gizi, stunting, sekaligus obesitas dan penyakit tidak menular. Edukasi gizi di sekolah, fasilitas kesehatan, dan ruang publik belum konsisten dan sering tidak terhubung dengan ketersediaan pangan sehat yang terjangkau. Kampanye pangan lokal bergizi dan berkelanjutan belum masif, sementara iklan produk tinggi kalori dan rendah nutrisi sangat dominan. Tanpa peningkatan literasi pangan sehat dan perubahan perilaku konsumsi, upaya memperbaiki sistem pangan dari sisi produksi tidak akan sepenuhnya meningkatkan kualitas kesehatan masyarakat.',
    'created_at' => '2025-12-07 20:23:17',
    'updated_at' => '2025-12-07 20:23:17',
  ),
  8 => 
  array (
    'id' => 9,
    'category_id' => 1,
    'order_number' => 9,
    'full_number' => '1.9',
    'title' => 'Lemahnya Sistem Monitoring dan Keamanan Pangan dari Hulu ke Hilir',
    'description' => 'Penerapan standar keamanan pangan di Indonesia masih belum konsisten di seluruh rantai pasok, mulai dari produksi primer, pengolahan, distribusi, hingga penjualan ritel. Pengawasan lapangan, kapasitas laboratorium uji, serta sistem pelaporan kontaminasi dan penarikan produk (recall) belum terintegrasi dalam satu platform data nasional. Pelaku usaha kecil kerap kesulitan memenuhi standar karena kurangnya pendampingan teknis dan biaya sertifikasi yang relatif tinggi. Akibatnya, kasus pangan tercemar, pemalsuan, dan produk tidak layak konsumsi masih terjadi dan menurunkan kepercayaan publik. Di pasar ekspor, lemahnya pemenuhan standar internasional menghambat daya saing produk pangan Indonesia. Tanpa sistem monitoring yang kuat dan transparan, perlindungan konsumen dan reputasi pangan nasional akan terus terancam.',
    'created_at' => '2025-12-07 20:23:32',
    'updated_at' => '2025-12-07 20:23:32',
  ),
  9 => 
  array (
    'id' => 10,
    'category_id' => 1,
    'order_number' => 10,
    'full_number' => '1.10',
    'title' => 'Krisis Regenerasi Petani dan Menurunnya Daya Tarik Profesi Pertanian.',
    'description' => 'Rata-rata usia petani di Indonesia terus meningkat sementara minat generasi muda untuk terjun ke sektor pertanian menurun. Profesi petani sering dipersepsikan sebagai pekerjaan dengan pendapatan rendah, risiko tinggi, dan akses terbatas terhadap teknologi, pembiayaan, serta jaminan sosial. Skema pelatihan kewirausahaan tani, inkubasi agritech, dan model bisnis yang menarik bagi talenta muda belum berkembang luas. Alih fungsi lahan dan ketiadaan skema kepemilikan atau sewa lahan yang ramah petani muda memperburuk situasi. Tanpa strategi regenerasi yang komprehensif yang mencakup insentif ekonomi, akses lahan, teknologi, dan pengakuan sosial, keberlanjutan sistem pangan nasional terancam oleh berkurangnya jumlah petani produktif dalam jangka menengah dan panjang.',
    'created_at' => '2025-12-07 20:23:48',
    'updated_at' => '2025-12-07 20:23:48',
  ),
  10 => 
  array (
    'id' => 11,
    'category_id' => 1,
    'order_number' => 11,
    'full_number' => '1.11',
    'title' => 'Lainnya Seputar Pangan',
    'description' => NULL,
    'created_at' => '2025-12-07 20:26:29',
    'updated_at' => '2025-12-07 20:26:29',
  ),
  11 => 
  array (
    'id' => 12,
    'category_id' => 2,
    'order_number' => 1,
    'full_number' => '2.1',
    'title' => 'Fragmentasi Data Kesehatan Nasional dan Lemahnya Interoperabilitas',
    'description' => 'Data kesehatan nasional masih tersebar di berbagai kementerian dan lembaga tanpa standar interoperabilitas yang baku, sehingga sulit digabungkan dan dimanfaatkan untuk perencanaan dan pengambilan keputusan berbasis bukti. Banyak sistem informasi dibangun sektoral dan tidak saling terhubung, sementara ekosistem Big Data kesehatan belum matang, baik dari sisi arsitektur, kualitas data, maupun tata kelola. Di sisi lain, literasi digital pelaku industri dan penyedia layanan kesehatan masih rendah, sehingga pemanfaatan analitik lanjutan dan integrasi data lintas platform berjalan lambat. Kondisi ini menghambat deteksi dini masalah kesehatan publik, respons terhadap kedaruratan, pemantauan program, serta pengembangan layanan kesehatan yang lebih presisi dan efisien. Tanpa transformasi menyeluruh, potensi data sebagai aset strategis bagi ketahanan dan kemandirian sistem kesehatan nasional akan terus terabaikan.',
    'created_at' => '2025-12-07 20:28:59',
    'updated_at' => '2025-12-07 20:30:13',
  ),
  12 => 
  array (
    'id' => 13,
    'category_id' => 2,
    'order_number' => 2,
    'full_number' => '2.2',
    'title' => 'Ketimpangan Distribusi Vaksin di Wilayah 3T dan Misinformasi Publik',
    'description' => 'Distribusi vaksin di wilayah tertinggal, terdepan, dan terluar (3T) masih belum merata karena keterbatasan infrastruktur rantai dingin, sarana transportasi, dan fasilitas penyimpanan yang memenuhi standar. Tantangan geografis berupa kepulauan dan daerah terpencil menyebabkan biaya logistik tinggi dan waktu tempuh panjang, sehingga risiko kerusakan vaksin meningkat. Di saat yang sama, maraknya misinformasi dan disinformasi kesehatan di masyarakat menurunkan kepercayaan terhadap program imunisasi dan menimbulkan keraguan menerima vaksin. Keterbatasan komunikasi risiko yang efektif serta kurangnya pelibatan tokoh lokal membuat koreksi informasi sulit menjangkau kelompok rentan. Akibatnya, cakupan vaksinasi di wilayah 3T tertinggal dibandingkan daerah lain, sehingga menimbulkan kesenjangan perlindungan kesehatan dan meningkatkan risiko kejadian luar biasa penyakit yang dapat dicegah dengan imunisasi.',
    'created_at' => '2025-12-07 20:30:26',
    'updated_at' => '2025-12-07 20:30:26',
  ),
  13 => 
  array (
    'id' => 14,
    'category_id' => 2,
    'order_number' => 3,
    'full_number' => '2.3',
    'title' => 'Tingginya Biaya Layanan Genomik dan Ketidakmerataan Akses Kedokteran Presisi',
    'description' => 'Biaya layanan genomik dan pemeriksaan genetik presisi di Indonesia masih relatif tinggi, menciptakan hambatan akses bagi mayoritas masyarakat. Tingginya biaya disebabkan ketergantungan pada teknologi impor yang mahal, belum adanya skala ekonomi dalam penawaran layanan, serta minimnya investasi publik dalam infrastruktur genomik lokal. Keterbatasan fasilitas laboratorium dan kurangnya tenaga ahli memperkuat posisi monopolistik penyedia layanan privat yang mempertahankan tarif premium. Integrasi ke dalam JKN dan pengembangan kapasitas lokal menjadi kunci menurunkan biaya operasional. Tanpa strategi pengendalian biaya berbasis kebijakan seperti subsidi perangkat, transfer teknologi, dan skema pembiayaan berkelanjutan, akses kedokteran presisi yang terjangkau bagi seluruh masyarakat akan terus terhambat.',
    'created_at' => '2025-12-07 20:30:44',
    'updated_at' => '2025-12-07 20:30:44',
  ),
  14 => 
  array (
    'id' => 15,
    'category_id' => 2,
    'order_number' => 4,
    'full_number' => '2.4',
    'title' => 'Sentralisasi Fasilitas Riset Kesehatan dan Tantangan Logistik Antar Pulau',
    'description' => 'Fasilitas riset kesehatan, laboratorium rujukan, dan pusat logistik utama masih terkonsentrasi di Pulau Jawa, menciptakan kesenjangan kapasitas riset dan layanan penunjang kesehatan di daerah lain. Keterbatasan infrastruktur regional menghambat kemampuan melakukan uji laboratorik lanjutan, uji klinis, dan pengembangan produk kesehatan lokal. Biaya distribusi logistik kesehatan, khususnya rantai dingin antar pulau, tetap tinggi karena terbatasnya moda transportasi andal, fasilitas penyimpanan berstandar, dan sistem manajemen rantai pasok terintegrasi. Kesenjangan ini berdampak pada lambatnya respons kedaruratan kesehatan regional, timpangnya akses teknologi kesehatan, dan terhambatnya pengembangan ekosistem riset merata. Desentralisasi strategis infrastruktur riset dan optimalisasi jaringan logistik regional menjadi kunci untuk meratakan kapasitas, menurunkan biaya distribusi, dan memperkuat ketahanan sistem kesehatan nasional.',
    'created_at' => '2025-12-07 20:31:20',
    'updated_at' => '2025-12-07 20:31:20',
  ),
  15 => 
  array (
    'id' => 16,
    'category_id' => 2,
    'order_number' => 5,
    'full_number' => '2.5',
    'title' => 'Harmonisasi Standar dan Pengawasan Kesehatan',
    'description' => 'Harmonisasi standar kesehatan nasional berlangsung lambat karena perbedaan interpretasi dan penerapan standar di berbagai tingkatan sistem kesehatan. Standar yang beragam menciptakan inkonsistensi kualitas layanan dan ketidakpastian operasional bagi stakeholder. Belum ada framework harmonisasi terstruktur dan mekanisme penetapan standar yang jelas untuk mencapai kesepakatan nasional yang terpadu dan mandatory. Lemahnya kapasitas pengawasan dalam hal SDM inspektur, peralatan monitoring lapangan, dan infrastruktur laboratorium rujukan mengakibatkan standar tidak diterapkan konsisten di seluruh wilayah. Penegakan standar kesehatan di lapangan berjalan tidak optimal karena keterbatasan sumber daya pengawasan dan mekanisme verifikasi kepatuhan yang terstruktur. Pengembangan standar kesehatan nasional yang unified dan kapasitas pengawasan lapangan yang kuat menjadi keharusan untuk menjamin konsistensi kualitas layanan kesehatan nasional.',
    'created_at' => '2025-12-07 21:00:56',
    'updated_at' => '2025-12-07 21:00:56',
  ),
  16 => 
  array (
    'id' => 17,
    'category_id' => 2,
    'order_number' => 6,
    'full_number' => '2.6',
    'title' => 'Pemanfaatan AI dan Big Data Kesehatan',
    'description' => 'Pemanfaatan kecerdasan artifisial (AI) dan Big Data di bidang kesehatan Indonesia masih berada pada tahap awal dan terbatas pada inisiatif skala kecil. Banyak fasilitas kesehatan belum memiliki infrastruktur komputasi berperforma tinggi, kualitas dan standar data yang memadai, serta arsitektur sistem yang mendukung integrasi data berskala besar. Keterbatasan talenta lintas bidang kesehatan, data science, dan rekayasa perangkat lunak menjadi hambatan utama pengembangan solusi AI andal. Kerangka regulasi untuk AI medis termasuk standar validasi, akuntabilitas, dan tata kelola risiko belum matang sehingga menimbulkan keraguan adopsi. Tanpa penguatan ekosistem infrastruktur, talenta, dan regulasi, potensi AI dan Big Data untuk meningkatkan efisiensi layanan, akurasi diagnosis, dan perencanaan kesehatan populasi belum dapat dimanfaatkan secara optimal.',
    'created_at' => '2025-12-07 21:01:12',
    'updated_at' => '2025-12-07 21:01:12',
  ),
  17 => 
  array (
    'id' => 18,
    'category_id' => 2,
    'order_number' => 7,
    'full_number' => '2.7',
    'title' => 'Literasi Digital dan Keamanan Siber',
    'description' => 'Literasi digital tenaga kesehatan masih beragam dan cenderung rendah, terutama di luar pusat-pusat rujukan besar. Banyak proses kerja masih dilakukan secara manual atau semi-digital, sehingga pemanfaatan sistem informasi kesehatan belum maksimal. Sistem keamanan siber untuk melindungi data pasien belum terbangun kuat dari sisi teknologi, prosedur, maupun budaya keamanan. Kebocoran data dan akses tidak sah berpotensi terjadi karena lemahnya pengelolaan akses, enkripsi, serta pemantauan insiden. Kesenjangan kompetensi digital menghambat transformasi layanan kesehatan berbasis teknologi dan meningkatkan risiko pelanggaran kerahasiaan data medis. Peningkatan kapasitas literasi digital dan penguatan keamanan siber menjadi prioritas untuk mendukung digitalisasi layanan kesehatan dan mempertahankan kepercayaan masyarakat.',
    'created_at' => '2025-12-07 21:01:45',
    'updated_at' => '2025-12-07 21:01:45',
  ),
  18 => 
  array (
    'id' => 19,
    'category_id' => 2,
    'order_number' => 8,
    'full_number' => '2.8',
    'title' => 'Isu Etik dan Sosial Teknologi Biomedis',
    'description' => 'Pemanfaatan teknologi biomedis maju seperti sel punca, rekayasa jaringan, dan terapi gen masih menghadapi berbagai isu etik dan sosial di Indonesia. Kerangka etik terkait informed consent, transparansi risiko, dan perlindungan kelompok rentan belum sepenuhnya dipahami dan diterapkan konsisten dalam penelitian maupun layanan. Asal-usul dan pengelolaan sumber sel punca, penggunaan bahan biologis manusia, serta pemanfaatannya untuk terapi menimbulkan pertanyaan moral, agama, dan sosial yang membutuhkan dialog luas. Mekanisme pengawasan etik belum mampu mengikuti kecepatan perkembangan teknologi. Pengembangan pedoman etik yang jelas, kapasitas komite etik yang kuat, dan komunikasi publik terbuka menjadi esensial untuk memaksimalkan manfaat teknologi biomedis dan mencegah konflik etik serta penolakan sosial.',
    'created_at' => '2025-12-07 21:02:00',
    'updated_at' => '2025-12-07 21:02:00',
  ),
  19 => 
  array (
    'id' => 20,
    'category_id' => 2,
    'order_number' => 9,
    'full_number' => '2.9',
    'title' => 'Kolaborasi Triple Helix dalam Inovasi Kesehatan',
    'description' => 'Kolaborasi antara pemerintah, akademisi, dan industri dalam riset dan hilirisasi produk kesehatan masih lemah dan terfragmentasi. Riset di perguruan tinggi banyak berhenti pada tahap publikasi tanpa berlanjut menjadi prototipe atau produk siap dipasarkan. Industri menghadapi keterbatasan akses terhadap hasil riset relevan, kepastian regulasi, dan dukungan insentif untuk pengembangan produk lokal. Mekanisme kolaborasi jangka panjang berbasis agenda riset nasional belum terbentuk kuat, sehingga inisiatif kerja sama bersifat sporadis. Penguatan kolaborasi triple helix melalui platform inovasi terstruktur, kepastian regulasi, dan insentif yang jelas menjadi kunci menghasilkan produk kesehatan berdaya saing dan mengurangi ketergantungan impor.',
    'created_at' => '2025-12-07 21:03:05',
    'updated_at' => '2025-12-07 21:03:05',
  ),
  20 => 
  array (
    'id' => 21,
    'category_id' => 2,
    'order_number' => 10,
    'full_number' => '2.10',
    'title' => 'Akselerasi Riset dan Inovasi Kesehatan Menuju Industri',
    'description' => 'Riset dan inovasi kesehatan di Indonesia masih belum optimal dalam mencapai tahap komersialisasi dan pengembangan industri yang mandiri. Banyak hasil riset berhenti pada tahap publikasi tanpa berlanjut menjadi prototipe atau produk siap dipasarkan. Ketiadaan mekanisme yang jelas untuk transformasi riset menjadi produk komersial menciptakan hambatan bagi peneliti untuk mengembangkan inovasi ke skala industri. Proses regulasi yang panjang dan tidak terstruktur menyulitkan pelaku inovasi memvalidasi dan memperoleh persetujuan produk secara efisien. Keterbatasan akses terhadap fasilitas uji klinis, laboratorium validasi, dan infrastruktur pendukung inovasi menghambat akselerasi dari riset menuju produk kompetitif. Pengembangan ekosistem inovasi komprehensif yang meliputi pathway regulasi progresif, fasilitas validasi produk, dan mekanisme inkubasi inovasi terstruktur menjadi kunci mengakselerasi transformasi riset menjadi produk kesehatan berdaya saing dan membangun kemandirian industri kesehatan nasional.',
    'created_at' => '2025-12-07 21:03:22',
    'updated_at' => '2025-12-07 21:03:22',
  ),
  21 => 
  array (
    'id' => 22,
    'category_id' => 2,
    'order_number' => 11,
    'full_number' => '2.11',
    'title' => 'Lainnya Seputar Kesehatan',
    'description' => NULL,
    'created_at' => '2025-12-07 21:03:31',
    'updated_at' => '2025-12-07 21:03:31',
  ),
  22 => 
  array (
    'id' => 23,
    'category_id' => 3,
    'order_number' => 1,
    'full_number' => '3.1',
    'title' => 'Pengembangan Energi Terbarukan dan Teknologi Mitigasi Iklim',
    'description' => 'Potensi bioprospecting untuk konversi menjadi biofuel dan bioenergi serta teknologi berbasis hayati untuk pengurangan emisi belum dikembangkan sistematis. Teknologi konversi dan produksi energi dari sumber daya hayati masih terbatas dan belum mencapai efisiensi optimal untuk skala komersial. Riset pengembangan biofuel generasi lanjut, bioenergi, dan teknologi mitigasi emisi karbon belum terintegrasi dalam strategi energi dan iklim nasional yang komprehensif. Keterbatasan infrastruktur pengolahan, kapasitas SDM dalam bioenergy engineering, dan mekanisme transisi menuju sistem energi berkelanjutan menghambat akselerasi dari riset menuju produksi skala industri. Penguatan riset aplikatif bioenergy, pengembangan teknologi konversi yang efisien, dan dukungan kebijakan yang mendorong inovasi energi terbarukan menjadi strategis untuk meningkatkan kontribusi energi terbarukan, mengurangi emisi karbon, dan mencapai kemandirian energi nasional.',
    'created_at' => '2025-12-07 21:06:12',
    'updated_at' => '2025-12-07 21:06:12',
  ),
  23 => 
  array (
    'id' => 24,
    'category_id' => 3,
    'order_number' => 2,
    'full_number' => '3.2',
    'title' => 'Terbatasnya Inovasi Hilirisasi Batubara Peringkat Rendah dan Gas untuk Transisi Energi',
    'description' => 'Inovasi pemanfaatan batubara peringkat rendah dan gas sebagai produk bernilai tinggi, seperti Compressed Natural Gas (CNG) dan liquid coal, masih minim dikembangkan sebagai bagian dari strategi transisi energi. Padahal, pengolahan lebih lanjut kedua sumber energi ini dapat mengurangi ketergantungan impor bahan bakar dan meningkatkan nilai tambah di dalam negeri. Proses gasifikasi dan upaya dedieselisasi pembangkit listrik tenaga uap (PLTU) yang carbon-intensive belum berjalan optimal akibat keterbatasan teknologi, insentif, dan skema pembiayaan. Selain itu, masih lemahnya integrasi antara agenda dekarbonisasi, kebutuhan energi terjangkau, dan roadmap hilirisasi membuat berbagai inisiatif berjalan parsial. Tanpa terobosan teknologi dan kebijakan yang mendorong hilirisasi batubara dan gas secara berkelanjutan, peluang menjadikannya sebagai solusi transisi energi yang lebih bersih dan efisien akan sulit tercapai.',
    'created_at' => '2025-12-07 21:06:28',
    'updated_at' => '2025-12-07 21:06:28',
  ),
  24 => 
  array (
    'id' => 25,
    'category_id' => 3,
    'order_number' => 3,
    'full_number' => '3.3',
    'title' => 'Kurangnya Pengembangan Waste-to-Energy dari Sampah Kota dan Residu Biomassa',
    'description' => 'Pemanfaatan municipal solid waste dan residu biomassa sebagai sumber energi alternatif melalui skema waste-to-energy masih jauh dari potensinya. Sebagian besar sampah kota masih berakhir di TPA terbuka atau hanya dikelola secara konvensional, menimbulkan masalah lingkungan dan kesehatan. Di saat yang sama, residu biomassa dari sektor pertanian, perkebunan, dan kehutanan belum diolah optimal sebagai sumber elektrifikasi, khususnya bagi daerah yang belum terjangkau jaringan listrik andal. Keterbatasan teknologi yang teruji, skema tarif yang menarik, kepastian offtaker, serta model kerja sama pemerintah–swasta menghambat tumbuhnya proyek waste-to-energy berskala komersial. Selain itu, kapasitas pemerintah daerah dalam merencanakan dan mengelola proyek energi berbasis limbah masih beragam. Tanpa penguatan ekosistem ini, peluang menjadikan limbah sebagai sumber energi terbarukan yang mendukung ketahanan energi akan terus terlewat.',
    'created_at' => '2025-12-07 21:06:56',
    'updated_at' => '2025-12-07 21:06:56',
  ),
  25 => 
  array (
    'id' => 26,
    'category_id' => 3,
    'order_number' => 4,
    'full_number' => '3.4',
    'title' => 'Pengembangan Inovasi dan Transformasi Bisnis dalam Transisi Energi',
    'description' => 'Strategi operasional industri energi masih berfokus pada optimalisasi biaya produksi, sementara inovasi dalam sistem produksi, business model, dan teknologi maju untuk transisi energi belum menjadi prioritas utama. Orientasi pada efisiensi biaya jangka pendek menghambat transformasi menuju sistem produksi yang kompetitif, berkelanjutan, dan selaras dengan target energi terbarukan nasional. Keterbatasan dalam mengalokasikan sumber daya untuk riset dan pengembangan teknologi energi bersih menghambat penciptaan nilai tambah dan diversifikasi portofolio energi yang mendukung pencapaian target net-zero emission. Kapasitas SDM dalam manajemen inovasi dan rekayasa proses energi berkelanjutan masih terbatas. Transformasi menuju business model inovatif berbasis energi terbarukan, pengembangan teknologi produksi efisien dan berkelanjutan, serta penguatan kapasitas SDM menjadi kunci meningkatkan kinerja industri dan pencapaian komitmen energi nasional.',
    'created_at' => '2025-12-07 21:07:10',
    'updated_at' => '2025-12-07 21:07:10',
  ),
  26 => 
  array (
    'id' => 27,
    'category_id' => 3,
    'order_number' => 5,
    'full_number' => '3.5',
    'title' => 'Terbatasnya Pengembangan Skema Natural Carbon Capture dalam Pasar Karbon',
    'description' => 'Upaya pengurangan emisi di sektor energi masih sangat bertumpu pada teknologi Carbon Capture and Storage/Utilization (CCS/CCUS) yang berbiaya tinggi dan kompleks, sementara skema natural carbon capture belum dikembangkan secara optimal. Potensi hutan, mangrove, lahan gambut, dan ekosistem biru sebagai penyerap karbon alami belum sepenuhnya diintegrasikan ke dalam mekanisme pasar karbon nasional maupun regional. Ketiadaan standar pengukuran, pelaporan, verifikasi, serta kelembagaan yang kuat menghambat pengembangan proyek berbasis solusi alam. Di sisi lain, keterlibatan masyarakat lokal dan mekanisme bagi hasil manfaat karbon masih belum jelas, sehingga mempengaruhi keberlanjutan program. Tanpa pengembangan skema natural carbon capture yang kredibel dan terintegrasi, Indonesia akan kesulitan memanfaatkan keunggulan sumber daya alamnya sebagai alternatif mitigasi emisi yang lebih terjangkau dan berkeadilan.',
    'created_at' => '2025-12-07 21:07:39',
    'updated_at' => '2025-12-07 21:07:39',
  ),
  27 => 
  array (
    'id' => 28,
    'category_id' => 3,
    'order_number' => 6,
    'full_number' => '3.6',
    'title' => 'Akselerasi Energi Berkelanjutan untuk Elektrifikasi Pedesaan',
    'description' => 'Akses listrik di pedesaan Indonesia masih terbatas dengan tingkat elektrifikasi rendah dan kualitas layanan belum merata, sementara potensi energi berkelanjutan lokal belum dimanfaatkan optimal. Pedesaan memiliki beragam potensi energi terbarukan seperti surya, angin, hidro mikro, dan biomassa, namun belum ada pendekatan terintegrasi untuk mengembangkan sistem energi sesuai konteks lokal. Struktur pasar listrik terpusat menghambat akses solusi energi terdesentralisasi dan teknologi smart grid untuk manajemen distribusi efisien. Skema insentif ekonomi dan kepastian keekonomian belum memberikan sinyal kuat untuk adopsi teknologi energi terbarukan lokal. Minimnya model bisnis fleksibel, literasi teknis masyarakat, dan akses pembiayaan hijau menghambat implementasi. Pengembangan ekosistem energi berkelanjutan terdesentralisasi berbasis potensi lokal, infrastruktur smart grid yang accessible, model bisnis inklusif, dan peningkatan kapasitas masyarakat menjadi kunci elektrifikasi pedesaan yang berkelanjutan.',
    'created_at' => '2025-12-07 21:08:04',
    'updated_at' => '2025-12-07 21:08:04',
  ),
  28 => 
  array (
    'id' => 29,
    'category_id' => 3,
    'order_number' => 7,
    'full_number' => '3.7',
    'title' => 'Pengembangan TKDN Berkualitas untuk Ekosistem Energi Berkelanjutan',
    'description' => 'Pengembangan Tingkat Komponen Dalam Negeri (TKDN) pada sektor energi berkelanjutan belum didukung strategi jangka panjang yang terarah dan berorientasi pada kualitas. Banyak komponen kunci masih bergantung pada impor, sementara kapasitas industri dalam negeri untuk memproduksi peralatan berkualitas tinggi dan kompetitif secara global belum matang. Kebijakan TKDN sering kali berfokus pada pencapaian persentase angka, bukan peningkatan kapabilitas teknologi dan kualitas manufaktur yang sesungguhnya. Belum ada roadmap pengembangan SDM, riset material, dan kemitraan industri yang kuat untuk mendukung kemandirian teknologi energi berkelanjutan. Investasi dalam riset dan pengembangan komponen berkualitas tinggi, standarisasi internasional, pengembangan kapasitas SDM manufaktur, dan kemitraan strategis antar industri menjadi keharusan untuk memperkuat ekosistem energi berkelanjutan yang mandiri dan kompetitif secara global.',
    'created_at' => '2025-12-07 21:09:50',
    'updated_at' => '2025-12-07 21:09:50',
  ),
  29 => 
  array (
    'id' => 30,
    'category_id' => 3,
    'order_number' => 8,
    'full_number' => '3.8',
    'title' => 'Minimnya Pemanfaatan IoT dan AI untuk Ekspansi Elektrifikasi di Daerah 3T',
    'description' => 'Pengembangan teknologi Internet of Things (IoT) dan Artificial Intelligence (AI) di sektor energi belum dimanfaatkan optimal untuk mengurangi kompleksitas logistik, infrastruktur, dan pemeliharaan sistem kelistrikan di daerah tertinggal, terdepan, dan terluar (3T). Padahal, pemantauan jarak jauh, prediksi gangguan, dan optimasi beban berbasis data dapat menurunkan biaya operasi dan meningkatkan keandalan sistem off-grid maupun microgrid. Keterbatasan kapasitas teknis operator lokal, infrastruktur komunikasi data, dan model bisnis layanan digital menghambat adopsi teknologi ini. Selain itu, belum ada paket solusi end-to-end yang terstandar untuk konteks daerah terpencil, sehingga setiap proyek berjalan ad hoc. Tanpa dorongan kuat pada inovasi digital, upaya peningkatan rasio elektrifikasi di 3T akan tetap menghadapi biaya tinggi dan kualitas layanan yang tidak merata.',
    'created_at' => '2025-12-07 21:10:08',
    'updated_at' => '2025-12-07 21:10:08',
  ),
  30 => 
  array (
    'id' => 31,
    'category_id' => 3,
    'order_number' => 9,
    'full_number' => '3.9',
    'title' => 'Hilirisasi Material Kritis untuk Ekosistem Energi Berkelanjutan',
    'description' => 'Material kritis seperti silika, litium, dan nikel yang melimpah di Indonesia belum sepenuhnya dihilirisasi menjadi produk bernilai tambah tinggi untuk mendukung industrialisasi energi berkelanjutan. Mayoritas masih diekspor dalam bentuk bahan mentah atau produk antara dengan nilai tambah terbatas. Keterbatasan fasilitas pengolahan lanjutan, teknologi pemurnian berstandar tinggi, dan kepastian pasar domestik untuk produk hilir menghambat tumbuhnya rantai pasok industri panel surya dan baterai nasional. Kebijakan hilirisasi belum sepenuhnya terintegrasi dengan roadmap transisi energi dan strategi investasi jangka panjang. Pengembangan fasilitas pengolahan dan pemurnian material kritis dengan standar internasional, integrasi hilirisasi dalam strategi transisi energi nasional, dan pembangunan rantai pasok energi berkelanjutan domestik menjadi kunci untuk meningkatkan nilai ekonomi dan posisi Indonesia dalam pasar global energi terbarukan.',
    'created_at' => '2025-12-07 21:10:25',
    'updated_at' => '2025-12-07 21:10:25',
  ),
  31 => 
  array (
    'id' => 32,
    'category_id' => 3,
    'order_number' => 10,
    'full_number' => '3.10',
    'title' => 'Perdagangan Listrik Lintas Negara untuk Akselerasi Energi Terbarukan',
    'description' => 'Skema perdagangan listrik lintas negara masih belum umum dan belum dimanfaatkan sebagai pendorong investasi pembangkit energi terbarukan di wilayah perbatasan dan kepulauan. Pembangunan energi terbarukan skala besar di wilayah strategis berpotensi menjadi basis ekspor listrik ke negara sekitar yang memiliki kebutuhan energi hijau tinggi dan daya beli kuat, namun peluang ini belum dioptimalkan. Keterbatasan kerangka operasional, infrastruktur interkoneksi, mekanisme tarif, dan perjanjian bilateral multiyears menghambat realisasi skema ini. Belum ada strategi menyeluruh yang mengaitkan potensi ekspor listrik terbarukan dengan pengembangan industri lokal dan kesejahteraan masyarakat setempat. Pembentukan kerangka operasional perdagangan energi lintas batas, pengembangan infrastruktur interkoneksi regional, mekanisme penetapan harga yang fair, dan strategi pembangunan ekonomi lokal berkelanjutan menjadi kunci membuka peluang ekonomi dan geopolitik dalam pasar energi regional.',
    'created_at' => '2025-12-07 21:10:42',
    'updated_at' => '2025-12-07 21:10:42',
  ),
  32 => 
  array (
    'id' => 33,
    'category_id' => 3,
    'order_number' => 11,
    'full_number' => '3.11',
    'title' => 'Lainnya Seputar Energi',
    'description' => NULL,
    'created_at' => '2025-12-07 21:10:49',
    'updated_at' => '2025-12-07 21:10:49',
  ),
  33 => 
  array (
    'id' => 34,
    'category_id' => 4,
    'order_number' => 1,
    'full_number' => '4.1',
    'title' => 'Ketiadaan Desain Kapal Series untuk Meningkatkan TKDN Industri Perkapalan',
    'description' => 'Industri galangan kapal Indonesia belum memiliki portofolio desain kapal series yang standar untuk berbagai tipe kapal niaga maupun pendukung logistik nasional. Setiap pembangunan kapal cenderung bersifat one-off, sehingga biaya desain dan produksi tinggi, waktu pembangunan panjang, dan efisiensi rantai pasok komponen tidak tercapai. Kondisi ini memperkuat ketergantungan pada kapal impor dan membuat kontribusi Indonesia dalam pembangunan kapal baru di kawasan tetap kecil, menyebabkan ketergantungan impor mencapai USD 3,31 miliar (2021-2024) dan kontribusi Indonesia dalam pembangunan kapal baru di ASEAN hanya 4%. Tanpa desain series yang teruji, sulit mendorong peningkatan TKDN karena industri pendukung tidak memiliki kepastian volume dan spesifikasi. Pengembangan standar desain kapal series nasional menjadi kunci untuk menurunkan biaya, memperkuat daya saing galangan, dan mendorong terbentuknya klaster industri komponen maritim di dalam negeri.',
    'created_at' => '2025-12-07 21:12:25',
    'updated_at' => '2025-12-07 21:12:25',
  ),
  34 => 
  array (
    'id' => 35,
    'category_id' => 4,
    'order_number' => 2,
    'full_number' => '4.2',
    'title' => 'Ketiadaan Ocean Digital Twin untuk Prediksi Maritim dan Optimalisasi Rute Pelayaran',
    'description' => 'Data kelautan Indonesia yang meliputi kondisi met-ocean, geografi, dan geologi saat ini tersebar di berbagai lembaga tanpa integrasi dan akses real-time. Padahal, sebagai negara dengan jutaan kilometer persegi perairan, Indonesia membutuhkan sistem ocean digital twin yang mampu memodelkan dan memprediksi cuaca maritim, arus, dan gelombang secara dinamis. Ketiadaan platform ini membuat perencanaan rute pelayaran, operasi kapal, dan kegiatan lepas pantai kurang optimal dan berisiko tinggi terhadap kecelakaan maupun keterlambatan. Informasi kritis sering disajikan terpisah dan tidak mudah dimanfaatkan operator kapal, otoritas pelabuhan, atau aparat keamanan laut. Tanpa digital twin yang terintegrasi, potensi efisiensi bahan bakar, peningkatan keselamatan pelayaran, dan dukungan terhadap ekonomi biru tidak dapat dimaksimalkan.',
    'created_at' => '2025-12-07 21:12:54',
    'updated_at' => '2025-12-07 21:12:54',
  ),
  35 => 
  array (
    'id' => 36,
    'category_id' => 4,
    'order_number' => 3,
    'full_number' => '4.3',
    'title' => 'Kelemahan Sistem Peringatan Dini dan Monitoring Kapal Real-Time',
    'description' => 'Indonesia mengalami 128 kecelakaan kapal pada 2024 (naik 37,6%). Peningkatan signifikan insiden kecelakaan kapal di Indonesia terkait erat dengan ketiadaan sistem peringatan dini dan manajemen lalu lintas kapal yang andal. Cuaca ekstrem sering tidak tertangkap sebagai early warning operasional, sementara tabrakan kapal di perairan padat terjadi karena tidak ada vessel traffic management system yang terintegrasi. Sistem pemantauan berbasis AIS yang ada memiliki cakupan terbatas dan belum terhubung dengan data cuaca, kondisi laut, maupun otoritas terkait secara real-time. Akibatnya, hilangnya komunikasi dengan kapal dan keterlambatan respons darurat masih sering terjadi. Tanpa modernisasi sistem monitoring kapal end-to-end, termasuk integrasi sensor, data cuaca, dan command center maritim, keselamatan pelayaran nasional akan tetap rentan terhadap gangguan alam maupun kelalaian operasional.',
    'created_at' => '2025-12-07 21:13:09',
    'updated_at' => '2025-12-07 21:13:09',
  ),
  36 => 
  array (
    'id' => 37,
    'category_id' => 4,
    'order_number' => 4,
    'full_number' => '4.4',
    'title' => 'Rendahnya Digitalisasi dan Otomasi Produksi Garam Rakyat',
    'description' => 'Produksi garam rakyat di Indonesia masih sangat bergantung pada pola tradisional yang sensitif terhadap cuaca dan sulit diprediksi. Proses evaporasi, kristalisasi, dan panen umumnya tidak dimonitor secara digital sehingga mutu garam fluktuatif dan produktivitas jauh di bawah potensi lahan. Keterbatasan sistem kontrol berbasis sensor dan data cuaca real-time membuat petambak sulit mengoptimalkan waktu pengisian, pengeringan, dan pemanenan. Lahan tambak yang terbatas tidak dimaksimalkan melalui peningkatan efisiensi proses, sehingga kapasitas pasok garam berkualitas tinggi tetap rendah. Tanpa adopsi teknologi digital dan otomasi sederhana yang terjangkau, sulit meningkatkan konsistensi kadar NaCl dan produktivitas per hektare, serta menghubungkan garam rakyat dengan rantai pasok industri yang membutuhkan standar mutu lebih ketat.',
    'created_at' => '2025-12-07 21:13:23',
    'updated_at' => '2025-12-07 21:13:23',
  ),
  37 => 
  array (
    'id' => 38,
    'category_id' => 4,
    'order_number' => 5,
    'full_number' => '4.5',
    'title' => 'Minimnya Diversifikasi Produk Turunan Garam dan Pemanfaatan Bittern',
    'description' => 'Industri garam nasional masih berfokus pada produksi garam konsumsi dan industri dasar, sementara pemanfaatan bittern sebagai sumber beragam mineral bernilai tinggi hampir belum dilakukan. Sebagian besar air sisa kristalisasi yang kaya magnesium, kalsium, kalium, dan bromin dibuang begitu saja, menimbulkan pemborosan sumber daya dan potensi pencemaran lingkungan. Ketiadaan teknologi dan model bisnis hilirisasi membuat peluang pengembangan produk specialty salt, garam kesehatan, dan suplemen mineral tidak tergarap. Petambak dan pelaku usaha kecil tidak memiliki insentif maupun akses teknologi untuk mengubah bittern menjadi produk komersial. Tanpa strategi terpadu untuk mengembangkan rantai nilai turunan garam, Indonesia akan terus kehilangan potensi nilai tambah dan ketergantungan pada impor produk mineral olahan tetap tinggi.',
    'created_at' => '2025-12-07 21:13:42',
    'updated_at' => '2025-12-07 21:13:42',
  ),
  38 => 
  array (
    'id' => 39,
    'category_id' => 4,
    'order_number' => 6,
    'full_number' => '4.6',
    'title' => 'Lemahnya Sistem Pengelolaan Sampah dan Transformasi Green Port di Pelabuhan',
    'description' => 'Banyak pelabuhan di Indonesia menghadapi masalah serius akumulasi sampah laut, limbah kapal, dan aliran sampah dari darat yang mengganggu operasi dan menimbulkan biaya pembersihan tinggi. Sampah yang tersangkut di propeller, masuk ke sistem pendingin, atau menghambat manuver kapal menurunkan efisiensi dan meningkatkan risiko kecelakaan. Pada saat yang sama, transformasi menuju green port berjalan lambat karena kebutuhan investasi awal peralatan ramah lingkungan sangat besar, regulasi dan insentif belum jelas, serta kapasitas SDM untuk mengoperasikan teknologi hijau masih terbatas. Belum ada sistem terintegrasi yang menggabungkan monitoring sampah real-time, pembersihan otomatis, dan roadmap transisi pelabuhan hijau yang feasible secara teknis dan ekonomi. Tanpa pendekatan menyeluruh, pelabuhan Indonesia akan tertinggal dari standar lingkungan global.',
    'created_at' => '2025-12-07 21:13:56',
    'updated_at' => '2025-12-07 21:13:56',
  ),
  39 => 
  array (
    'id' => 40,
    'category_id' => 4,
    'order_number' => 7,
    'full_number' => '4.7',
    'title' => 'Tingginya Ketergantungan Impor Garam Industri dan Farmasi',
    'description' => 'Indonesia masih sangat bergantung pada impor garam industri dan farmasi sebesar 2,7 juta ton (2024) dengan nilai USD 270-400, meskipun produksi garam konsumsi telah mencapai swasembada. Kapasitas refining domestik terbatas dan hanya mampu memenuhi sebagian kecil kebutuhan, sementara mutu garam rakyat sebagai bahan baku belum konsisten dan sangat dipengaruhi cuaca serta metode produksi tradisional, padahal industri CAP (Chlor Alkali Plant), farmasi, dan pangan olahan membutuhkan garam dengan NaCl >97% bahkan ultrapure (>99.5% untuk farmasi) namun Indonesia hanya memiliki 2-3 fasilitas refining dengan kapasitas total <300,000 ton/tahun sedangkan kebutuhan 3+ juta ton/tahun. Biaya produksi lokal relatif tinggi dan tidak stabil, membuat garam impor yang lebih murah dan seragam mutunya menjadi pilihan utama industri kimia, pangan olahan, dan farmasi. Di sisi regulasi, pengaturan HS Code (2501.00) dan instrumen proteksi belum membedakan jenis garam bernilai tambah tinggi, sehingga tidak memberi sinyal kuat bagi investasi refining. Keterbatasan kompetensi QA/QC dan fasilitas laboratorium farmasi memperburuk kemampuan menghasilkan garam ultrapure sesuai standar farmakope internasional.',
    'created_at' => '2025-12-07 21:14:14',
    'updated_at' => '2025-12-07 21:14:14',
  ),
  40 => 
  array (
    'id' => 41,
    'category_id' => 4,
    'order_number' => 8,
    'full_number' => '4.8',
    'title' => 'Terbatasnya Teknologi AUV untuk Eksplorasi dan Monitoring Laut',
    'description' => 'Ketersediaan dan penguasaan teknologi Autonomous Underwater Vehicle (AUV) di Indonesia masih sangat terbatas, padahal kebutuhan eksplorasi dan pemantauan laut terus meningkat. Wilayah perairan yang luas, kompleks, dan strategis memerlukan observasi berkelanjutan untuk kepentingan riset, pemetaan dasar laut, pemantauan ekosistem, keamanan maritim, hingga pengembangan industri energi dan mineral laut dalam. Ketergantungan pada AUV impor membuat biaya operasi tinggi dan membatasi frekuensi misi survei. Selain itu, kapasitas rekayasa dan integrasi sensor lokal untuk berbagai kebutuhan spesifik Indonesia belum terbentuk kuat. Tanpa pengembangan teknologi AUV nasional yang andal dan ekonomis, pemanfaatan sumber daya laut dan pengawasan wilayah perairan tidak akan optimal, serta Indonesia berpotensi tertinggal dalam kompetisi ekonomi biru regional.',
    'created_at' => '2025-12-07 21:14:29',
    'updated_at' => '2025-12-07 21:14:29',
  ),
  41 => 
  array (
    'id' => 42,
    'category_id' => 4,
    'order_number' => 9,
    'full_number' => '4.9',
    'title' => 'Rendahnya Pemanfaatan IoT dan Digitalisasi pada Budidaya Ikan KJA',
    'description' => 'Sebagian besar keramba jaring apung (KJA) di Indonesia masih dikelola secara tradisional dengan pemantauan manual terhadap pakan, kualitas air, dan kondisi ikan. Keterbatasan data real-time membuat petambak sulit mengoptimalkan kepadatan tebar, pola pemberian pakan, dan tindakan pencegahan penyakit, sehingga produktivitas rendah dan tingkat kematian ikan tinggi. Belum tersedia solusi IoT yang terjangkau dan terstandar untuk memonitor parameter penting seperti suhu, oksigen terlarut, dan arus secara kontinu. Integrasi data dengan sistem prediksi cuaca laut juga belum umum digunakan. Tanpa digitalisasi proses budidaya, sulit meningkatkan efisiensi biaya pakan, stabilitas produksi, serta daya saing produk ikan laut Indonesia di pasar domestik maupun ekspor.',
    'created_at' => '2025-12-07 21:14:43',
    'updated_at' => '2025-12-07 21:14:43',
  ),
  42 => 
  array (
    'id' => 43,
    'category_id' => 4,
    'order_number' => 10,
    'full_number' => '4.10',
    'title' => 'Ketiadaan Sistem Logistik Maritim Cerdas untuk Optimalisasi Tol Laut',
    'description' => 'Program Tol Laut dan konektivitas maritim nasional masih menghadapi masalah ketidakseimbangan muatan dan biaya logistik yang tinggi, terutama pada rute barat–timur. Kapasitas angkut kapal sering tidak terisi optimal, sementara informasi ketersediaan ruang kargo, jenis muatan, dan rute kapal tersebar di berbagai sistem yang tidak saling terhubung. Belum ada platform digital nasional yang mengintegrasikan database muatan real-time, kapasitas kapal, optimasi rute berbasis AI, pelacakan kargo end-to-end, dan sistem pelabuhan untuk bongkar-muat efisien. Akibatnya, biaya logistik tetap jauh di atas negara maju dan menghambat daya saing produk dari wilayah timur. Tanpa sistem logistik maritim cerdas, potensi Tol Laut sebagai tulang punggung distribusi nasional tidak akan tercapai sepenuhnya.',
    'created_at' => '2025-12-07 21:17:02',
    'updated_at' => '2025-12-07 21:17:02',
  ),
  43 => 
  array (
    'id' => 44,
    'category_id' => 4,
    'order_number' => 11,
    'full_number' => '4.11',
    'title' => 'Lainnya Seputar Maritim',
    'description' => NULL,
    'created_at' => '2025-12-07 21:17:11',
    'updated_at' => '2025-12-07 21:17:11',
  ),
  44 => 
  array (
    'id' => 45,
    'category_id' => 5,
    'order_number' => 1,
    'full_number' => '5.1',
    'title' => 'Ketergantungan Impor Teknologi Kunci Pertahanan dan Fragmentasi Ekosistem Industri Lokal',
    'description' => 'Indonesia menghadapi ketergantungan struktural pada teknologi kunci impor dalam industri pertahanan. Teknologi fundamental seperti material strategis, elektronika, dan semikonduktor sepenuhnya berasal dari luar. Kapasitas manufaktur lokal terbatas pada tahap awal produksi tanpa penguasaan teknologi dasar. Ekosistem industri pertahanan yang meliputi produsen utama, startup pertahanan, dan supplier tier dua hingga empat khusus beroperasi terpisah-pisah tanpa sinergi koordinasi. Setiap entitas mengembangkan teknologi pertahanan secara mandiri, menghasilkan duplikasi upaya dan inefisiensi ekonomi. Pola pengembangan teknologi pertahanan lokal tidak terstruktur dengan baik, tidak ada roadmap jangka panjang yang konsisten, dan tidak ada mekanisme transfer pengetahuan sistematis antar produsen. Spesialisasi industri pertahanan lokal tidak berkembang karena permintaan tidak transparan dan volume pengadaan tidak predictable. Kemandirian pertahanan memerlukan terobosan dalam penguasaan teknologi fundamental pertahanan melalui ekosistem industri pertahanan yang terkoordinasi, terintegrasi, dan fokus pada spesifikasi kebutuhan operasional jangka panjang.',
    'created_at' => '2025-12-07 21:25:05',
    'updated_at' => '2025-12-07 21:25:05',
  ),
  45 => 
  array (
    'id' => 46,
    'category_id' => 5,
    'order_number' => 2,
    'full_number' => '5.2',
    'title' => 'Keterbatasan Kapasitas Manufaktur Lokal dan Penguasaan Teknologi Tier Dua hingga Empat',
    'description' => 'Industri pertahanan lokal terbatas pada manufaktur tier satu dengan assembly dan sub-assembly dasar tanpa penguasaan penuh desain dan rekayasa teknologi. Supplier komponen tier dua, tiga, dan empat masih sangat terbatas jumlah dan kapabilitas teknologinya. Kemampuan memproduksi bahan baku strategis seperti material komposit, elektronika presisi, komponen optik, dan subsistem khusus masih sangat rendah. Ini mengakibatkan industri lokal masih bergantung pada impor untuk sebagian besar komponen dan material fundamental. Rantai pasok lokal tidak solid sehingga efisiensi produksi rendah, lead time panjang, dan kualitas konsistensi sulit dijaga. Penguasaan teknologi manufaktur tier dua hingga empat memerlukan komitmen jangka panjang terhadap pengembangan kapabilitas teknis, transfer pengetahuan dari tier satu, pembelajaran sistematis dari prototipe ke produksi massal. Saat ini, industri tier dua hingga empat tidak memiliki akses mudah terhadap pengetahuan teknis, standar industri, atau best practice manufaktur yang dimiliki tier satu. Fragmentasi dan isolasi industri mengakibatkan setiap tier mengembangkan capabilitas mandiri tanpa sinergi. Pengembangan kapabilitas manufaktur tier dua hingga empat adalah prasyarat untuk mencapai integrasi vertikal rantai pasok dan kemandirian manufaktur alutsista secara menyeluruh.',
    'created_at' => '2025-12-07 21:25:25',
    'updated_at' => '2025-12-07 21:25:25',
  ),
  46 => 
  array (
    'id' => 47,
    'category_id' => 5,
    'order_number' => 3,
    'full_number' => '5.3',
    'title' => 'Fragmentasi Ekosistem Drone Militer, Intransparansi Kebutuhan Operasional, dan Ketiadaan Standardisasi Komunikasi',
    'description' => 'Indonesia memiliki pasar drone militer yang signifikan dengan kebutuhan untuk pengintaian, surveillance, dan operasi tempur. Permintaan dari institusi pengguna juga berdimensi ekspor ke pasar regional militer. Namun industri lokal gagal merebut pangsa pasar karena ekosistem terfragmentasi tanpa koordinasi. Produsen utama menghasilkan platform berkualitas tetapi supplier komponen tier dua dan tiga masih terbatas, standardisasi komunikasi antar platform belum ada sehingga setiap produsen menggunakan datalink proprietary yang tidak dapat saling beroperasi. Penelitian drone militer dilakukan di berbagai institusi tanpa sinkronisasi terpadu dengan kebutuhan operasional pengguna. Permintaan drone militer juga intransparansi karena tidak ada pemetaan komprehensif kebutuhan operasional jangka panjang, spesifikasi sering berubah di tengah proyek mengakibatkan ketidakpastian perencanaan industri, dan roadmap pengadaan tidak jelas. Intransparansi ini mengakibatkan mismatch antara kapabilitas industri lokal dan kebutuhan operasional pengguna akhir. Ekosistem drone militer yang efektif memerlukan visi bersama, kepemimpinan yang kuat, transparansi kebutuhan operasional jangka panjang, dan standardisasi komunikasi antarplatform drone.',
    'created_at' => '2025-12-07 21:25:44',
    'updated_at' => '2025-12-07 21:25:44',
  ),
  47 => 
  array (
    'id' => 48,
    'category_id' => 5,
    'order_number' => 4,
    'full_number' => '5.4',
    'title' => 'Keterbatasan Teknologi Komponen Drone, Akses Manufaktur Tertutup, dan Ketiadaan Fasilitas Bersama',
    'description' => 'Teknologi desain drone sudah dikuasai institusi lokal tetapi teknologi komponen kritis masih sepenuhnya bergantung pada impor. Sistem kendali penerbangan lokal masih tahap awal, sensor seperti kamera dan lidar semuanya impor, propulsi terbatas untuk skala kecil. Kandungan lokal hanya sekitar empat puluh hingga lima puluh persen sehingga margin keuntungan industri besar hilang ke supplier asing dan biaya produksi lokal tidak kompetitif. Hambatan krusial adalah akses manufaktur tertutup bagi startup dan usaha kecil menengah. Startup drone lokal memiliki inovasi menarik tetapi tidak dapat mengakses mesin perkakas presisi, pelapisan komposit, perakitan papan sirkuit tercetak yang memerlukan investasi modal besar. Fasilitas manufaktur canggih ada tetapi tidak membuka akses bagi startup. Model fasilitas bersama di mana kapasitas diakses bersama belum ada, memaksa startup mengalihdayakan ke luar atau tidak dapat berkembang. Momentum scaling lemah karena pasar kecil, permintaan tidak pasti, dan profitabilitas belum jelas. Kemampuan lokalisasi komponen drone, pembukaan akses manufaktur melalui fasilitas bersama, dan skema pendukung kapasitas merupakan prasyarat untuk memberdayakan startup dan meningkatkan viabilitas industri drone lokal.',
    'created_at' => '2025-12-07 21:26:01',
    'updated_at' => '2025-12-07 21:26:01',
  ),
  48 => 
  array (
    'id' => 49,
    'category_id' => 5,
    'order_number' => 5,
    'full_number' => '5.5',
    'title' => 'Lemahnya Ekosistem Pertahanan Siber, Ketergantungan Teknologi Penuh, dan Diperlukan Mekanisme Pembangunan Kepercayaan',
    'description' => 'Indonesia belum memiliki ekosistem pertahanan siber yang matang dan terstruktur. Industri lokal keamanan siber sangat kecil dan berorientasi pasar komersial bukan pertahanan, komponen perangkat keras pertahanan siber belum berkembang mengikuti tantangan saat ini. Ekosistem yang solid memerlukan kerangka kerja komprehensif, institusi yang kuat, dan saluran pengembangan talenta yang semuanya masih kurang. Ketergantungan pada teknologi asing sepenuhnya di mana seluruh infrastruktur pertahanan siber seperti antivirus, firewall, dan enkripsi berasal dari vendor asing. Vendor asing memahami detail sistem Indonesia secara intim dan memiliki potensi akses tersembunyi ke sistem. Efek penguncian teknologi sangat kuat dengan switching cost tinggi. Dari perspektif pertahanan strategis, ketergantungan infrastruktur siber pada pihak asing merupakan kerentanan kritis dan ancaman keamanan nasional. Juga, transfer teknologi siber dari mitra strategis terhambat karena masalah kepercayaan. Mekanisme alternatif membangun kepercayaan perlu dikembangkan melalui kolaborasi teknis, fasilitas penelitian bersama, dan protokol keamanan yang kredibel untuk memfasilitasi transfer teknologi pertahanan siber.',
    'created_at' => '2025-12-07 21:26:15',
    'updated_at' => '2025-12-07 21:26:15',
  ),
  49 => 
  array (
    'id' => 50,
    'category_id' => 5,
    'order_number' => 6,
    'full_number' => '5.6',
    'title' => 'Perangkat Keras Siber Tertinggal, Desain Keamanan Pengguna Terabaikan, dan Hambatan Komersialisasi Hasil Riset',
    'description' => 'Industri keamanan siber lokal memiliki kekuatan dalam perangkat lunak dan algoritma seperti enkripsi dan deteksi anomali tetapi perangkat keras pertahanan siber lokal hampir tidak ada. Prosesor keamanan, modul terpercaya, dan enkripsi perangkat keras semuanya impor. Pengembangan perangkat keras memerlukan keahlian mendalam tentang semikonduktor dan desain sirkuit yang sangat terbatas. Startup keamanan siber fokus pada perangkat lunak karena investasi modal lebih rendah dan waktu masuk pasar lebih cepat. Algoritma kriptografi nasional belum siap produksi, enkripsi suara dan jaringan pribadi virtual lokal masih tahap penelitian tetapi tidak dikomersialisasikan. Kematangan penelitian dan pengembangan tidak mencukupi untuk bersaing di pasar internasional. Hasil penelitian dan pengembangan sulit dikomersialisasikan karena hambatan administratif, prosedur kompleks, dan jalur menuju pasar yang tidak jelas. Juga, sistem keamanan siber lokal sering dirancang tanpa mempertimbangkan kemudahan penggunaan pengguna. Keamanan yang sulit digunakan menyebabkan frustrasi dan workaround yang melemahkan efektivitas keamanan. Standar keamanan mudah digunakan perlu dikembangkan dengan mempertimbangkan kemudahan dipelajari, efisiensi kerja, kemudahan diingat, dan meminimalkan kesalahan penggunaan. Kemandirian siber memerlukan program lokalisasi perangkat keras, claritas jalur komersialisasi teknologi, dan desain keamanan yang mempertimbangkan faktor pengguna.',
    'created_at' => '2025-12-07 21:26:35',
    'updated_at' => '2025-12-07 21:26:35',
  ),
  50 => 
  array (
    'id' => 51,
    'category_id' => 5,
    'order_number' => 7,
    'full_number' => '5.7',
    'title' => 'Ketertinggalan Teknologi Kuantum dan Kesenjangan SDM',
    'description' => 'Indonesia belum memiliki industri atau momentum penelitian signifikan dalam teknologi kuantum yang mencakup komputasi, komunikasi, dan sensor kuantum. Inisiatif riset baru ada tetapi belum terkoordinasi tanpa peta jalan terintegrasi. Ekosistem penelitian menuju industri tidak terbentuk. Infrastruktur penelitian khusus seperti fasilitas kriogenik dan optik presisi sangat terbatas. Kompetisi global dalam teknologi kuantum sangat sengit dengan negara-negara kuat menginvestasikan sumber daya besar. Indonesia berisiko tertinggal dalam perkembangan teknologi kuantum dengan kesenjangan kemampuan besar dalam lanskap pertahanan masa depan. Pasar teknologi kuantum global berkembang pesat tetapi Indonesia belum memiliki pemain industri. Sumber daya manusia di bidang kuantum sangat terbatas sementara kebutuhan untuk mengembangkan teknologi kuantum indigenous mencapai puluhan peneliti tingkat doktor. Lintasan perkembangan saat ini sangat tidak mencukupi. Program pendidikan untuk teknologi kuantum lokal belum sepenuhnya dikembangkan. Pengembangan teknologi kuantum memerlukan strategi berorientasi pada misi strategis mengatasi ancaman di masa depan dengan fokus pada spesifikasi teknologi jangka panjang. Pendekatan ini akan memastikan konsistensi pengembangan teknologi dan transfer pengetahuan ke industri lokal.',
    'created_at' => '2025-12-07 21:26:49',
    'updated_at' => '2025-12-07 21:26:49',
  ),
  51 => 
  array (
    'id' => 52,
    'category_id' => 5,
    'order_number' => 8,
    'full_number' => '5.8',
    'title' => 'Kemampuan Satelit Belum Terintegrasi dan Industri Ruang Angkasa Terbatas',
    'description' => 'Lembaga penyelenggara satelit memiliki keahlian bertahun-tahun dalam operasi dan manufaktur satelit dengan pencapaian signifikan dalam pengembangan satelit komunikasi nasional. Namun kemampuan satelit belum terintegrasi dengan sistem pertahanan terintegrasi atau strategi pertahanan di masa depan. Satelit optik untuk dekade ketiga direncanakan tetapi pengembangan belum dimulai serius. Industri layanan peluncuran satelit tidak ada. Komunikasi satelit untuk pertahanan dengan enkripsi standar nasional belum tersedia. Koordinasi antara lembaga satelit, lembaga penelitian nasional, dan institusi penelitian untuk mengembangkan kemampuan ruang angkasa lokal sangat terbatas. Harga satelit menurun dan resolusi meningkat tetapi akses komponen kritis dibatasi oleh kontrol ekspor internasional. Ancaman pertahanan masa depan menunjukkan masalah asimetri biaya dengan pertahanan drone dan misil sangat mahal sementara serangan relatif murah.',
    'created_at' => '2025-12-07 21:27:05',
    'updated_at' => '2025-12-07 21:27:05',
  ),
  52 => 
  array (
    'id' => 53,
    'category_id' => 5,
    'order_number' => 9,
    'full_number' => '5.9',
    'title' => 'Ketergantungan Impor Alutsista Militer, Pasar Domestik Tertutup, dan Intransparansi Kebutuhan Operasional Jangka Panjang',
    'description' => 'Ketergantungan pertahanan Indonesia pada impor alutsista sangat tinggi dari anggaran pengadaan militer. Teknologi kunci alutsista seperti mesin penerbang, radar canggih, sistem kendali api, dan sensor optik semuanya impor tanpa alternatif supply lokal. Kerentanan rantai pasokan tinggi terhadap embargo, perang dagang, dan ketegangan geopolitik dalam situasi krisis. Kemandirian strategis operasional rendah karena keputusan pengadaan alutsista dipengaruhi ketersediaan teknologi asing. Pasar domestik alutsista militer relatif tertutup untuk produsen lokal karena preferensi terhadap vendor asing terbukti dan teruji, pangsa pasar lokal sangat kecil dan berkembang lambat. Spesifikasi kebutuhan alutsista tersebar di berbagai program tanpa rencana terpadu jangka panjang. Jadwal pengadaan tidak dapat diprediksi sehingga industri lokal tidak dapat merencanakan pengembangan kapasitas manufaktur atau penelitian teknologi.',
    'created_at' => '2025-12-07 21:27:21',
    'updated_at' => '2025-12-07 21:27:21',
  ),
  53 => 
  array (
    'id' => 54,
    'category_id' => 5,
    'order_number' => 10,
    'full_number' => '5.10',
    'title' => 'Sistem Pertahanan Terfragmentasi, Interoperabilitas Terbatas, Arsitektur Sistem Terintegrasi Belum Terdefinisi, Kedaulatan Data Belum Teratasi',
    'description' => 'Sistem pertahanan Indonesia masih berbasis platform individual bukan arsitektur berbasis jaringan terintegrasi. Interoperabilitas antarplatform minimal di mana radar, komunikasi, dan sistem senjata berjalan terisolasi tanpa integrasi data terpadu. Setiap sistem memiliki basis data terpisah dan antarmuka proprietary yang tidak kompatibel. Arsitektur berbasis jaringan merupakan pergeseran paradigma yang diperlukan untuk ancaman pertahanan modern dengan kesadaran bersama, pengambilan keputusan cepat, dan operasi efisien. Infrastruktur komunikasi untuk sistem pertahanan terintegrasi sangat terbatas dalam kapasitas dan jangkauan. Komunikasi radio ada tetapi teknologi ketinggalan zaman, jaringan inti tidak memiliki redundansi, lebar pita tidak cukup untuk aplikasi intensif data. Ancaman berbasis jaringan memerlukan integrasi tautan data standardisasi, enkripsi aman, dan infrastruktur manajemen kunci untuk mengendalikan pertukaran informasi. Indonesia belum mengembangkan arsitektur sistem pertahanan terintegrasi yang mengintegrasikan ketiga elemen. Juga, data strategis pemerintah dan pertahanan berpotensi rentan jika disimpan di infrastruktur asing. Indonesia memerlukan lokalisasi untuk data strategis di fasilitas aman lokal. Ketiadaan arsitektur berbasis jaringan ditambah kedaulatan data yang belum teratasi akan membatasi kemampuan pertahanan terhadap ancaman hibrid modern.',
    'created_at' => '2025-12-07 21:27:47',
    'updated_at' => '2025-12-07 21:27:47',
  ),
  54 => 
  array (
    'id' => 55,
    'category_id' => 5,
    'order_number' => 11,
    'full_number' => '5.11',
    'title' => 'Lainnya Seputar Pertahanan',
    'description' => NULL,
    'created_at' => '2025-12-07 21:27:56',
    'updated_at' => '2025-12-07 21:27:56',
  ),
  55 => 
  array (
    'id' => 56,
    'category_id' => 6,
    'order_number' => 1,
    'full_number' => '6.1',
    'title' => 'Ketiadaan Rantai Pasok Semikonduktor Nasional yang Terintegrasi',
    'description' => 'Rantai pasok semikonduktor di Indonesia masih terfragmentasi dan sangat bergantung pada impor bahan baku, peralatan, dan komponen dari negara lain. Belum ada ekosistem yang menghubungkan secara utuh sektor riset, industri, dan pengguna akhir, sehingga upaya pengembangan chip lokal berjalan parsial dan tidak mencapai skala ekonomi. Keterbatasan integrasi ini membuat koordinasi antar pelaku sulit, mulai dari desain, wafer fab, hingga assembling dan integrasi ke produk elektronik. Di sisi lain, belum tersedia kebijakan komprehensif yang memetakan peran dan insentif di setiap mata rantai nilai. Akibatnya, Indonesia lebih berperan sebagai pasar konsumsi, bukan produsen bernilai tambah dalam industri semikonduktor global.',
    'created_at' => '2025-12-07 21:32:06',
    'updated_at' => '2025-12-07 21:32:06',
  ),
  56 => 
  array (
    'id' => 57,
    'category_id' => 6,
    'order_number' => 2,
    'full_number' => '6.2',
    'title' => 'Terbatasnya Kapasitas Desain, Manufaktur, dan Pengujian Semikonduktor',
    'description' => 'Kapasitas industri nasional di bidang desain chip, manufaktur, dan pengujian semikonduktor masih sangat terbatas dan berskala kecil. Jumlah pelaku desain chip sedikit, dengan kemampuan yang belum mampu memenuhi kebutuhan pasar domestik, apalagi bersaing di tingkat internasional. Fasilitas manufaktur seperti wafer fabrication dan Assembly, Testing, Packaging (ATP) masih minim dan belum terintegrasi dengan rantai pasok global, sehingga nilai tambah produksi banyak dinikmati di luar negeri. Keterbatasan ini membuat Indonesia sulit menjadi basis produksi strategis bagi industri elektronik dan AI. Tanpa investasi besar dan penguatan kapabilitas di tiga mata rantai utama tersebut, ketergantungan pada produk impor akan terus berlanjut dan ruang inovasi industri lokal tetap sempit.',
    'created_at' => '2025-12-07 21:32:43',
    'updated_at' => '2025-12-07 21:32:43',
  ),
  57 => 
  array (
    'id' => 58,
    'category_id' => 6,
    'order_number' => 3,
    'full_number' => '6.3',
    'title' => 'Minimnya Kepemilikan dan Perlindungan IP di Sektor Semikonduktor',
    'description' => 'Aktivitas riset dan inovasi semikonduktor di Indonesia belum banyak berujung pada paten, desain terproteksi, atau portofolio Intellectual Property (IP) yang kuat. Banyak hasil penelitian berhenti pada publikasi atau prototipe laboratorium tanpa dilanjutkan ke proses pendaftaran dan komersialisasi IP. Rendahnya kesadaran pentingnya perlindungan IP, terbatasnya dukungan hukum dan pendampingan komersialisasi, serta belum jelasnya model bagi hasil antara peneliti dan institusi membuat motivasi menciptakan IP lemah. Akibatnya, posisi Indonesia dalam rantai nilai global lebih sebagai pengguna teknologi, bukan pemilik lisensi atau standar. Tanpa penguatan budaya IP dan ekosistem komersialisasi, peluang memperoleh nilai ekonomi dari inovasi semikonduktor akan terus hilang.',
    'created_at' => '2025-12-07 21:42:39',
    'updated_at' => '2025-12-07 21:42:39',
  ),
  58 => 
  array (
    'id' => 59,
    'category_id' => 6,
    'order_number' => 4,
    'full_number' => '6.4',
    'title' => 'Lemahnya Strategi Keberlanjutan Perusahaan Semikonduktor dan AI',
    'description' => 'Banyak perusahaan berbasis semikonduktor dan AI di Indonesia masih berorientasi jangka pendek, fokus pada kelangsungan usaha harian tanpa strategi keberlanjutan yang matang. Isu efisiensi energi, jejak karbon, dan pengelolaan limbah proses produksi belum terintegrasi dalam perencanaan bisnis jangka panjang. Di sisi lain, akses terhadap investasi hijau dan pembiayaan yang mensyaratkan standar lingkungan, sosial, dan tata kelola (ESG) masih terbatas. Kondisi ini berpotensi mengurangi daya saing ketika pasar global semakin menuntut praktik industri yang berkelanjutan dan transparan. Tanpa roadmap keberlanjutan yang jelas dan dukungan kebijakan, perusahaan semikonduktor dan AI nasional akan sulit menarik mitra internasional maupun investor yang berorientasi jangka panjang.',
    'created_at' => '2025-12-07 21:43:32',
    'updated_at' => '2025-12-07 21:43:32',
  ),
  59 => 
  array (
    'id' => 60,
    'category_id' => 6,
    'order_number' => 5,
    'full_number' => '6.5',
    'title' => 'Ketiadaan Pilot Project Semikonduktor dalam Sistem Pengadaan Pemerintah',
    'description' => 'Hingga kini belum terdapat pilot project semikonduktor nasional yang terintegrasi dengan mekanisme pengadaan barang dan jasa pemerintah sebagai jalur adopsi awal. Produk chip dan komponen lokal tidak memiliki “pasar pertama” yang dapat digunakan untuk membuktikan kinerja dan keandalannya di aplikasi nyata. Tanpa skema pengadaan yang mendukung penggunaan teknologi dalam negeri, validasi teknologi dan pembelajaran produksi dalam skala terbatas menjadi terhambat. Hal ini menurunkan kepercayaan industri dan investor terhadap kelayakan komersial produk semikonduktor lokal. Ketiadaan pilot project yang dikaitkan dengan pengadaan publik membuat riset nasional sulit naik kelas dari prototipe ke implementasi dan memperlambat pertumbuhan ekosistem industri semikonduktor domestik.',
    'created_at' => '2025-12-07 21:44:05',
    'updated_at' => '2025-12-07 21:44:05',
  ),
  60 => 
  array (
    'id' => 61,
    'category_id' => 6,
    'order_number' => 6,
    'full_number' => '6.6',
    'title' => 'Terbatasnya Skema Pendanaan untuk Ekosistem Semikonduktor dan AI',
    'description' => 'Hingga kini belum terdapat pilot project semikonduktor nasional yang terintegrasi dengan mekanisme pengadaan barang dan jasa pemerintah sebagai jalur adopsi awal. Produk chip dan komponen lokal tidak memiliki “pasar pertama” yang dapat digunakan untuk membuktikan kinerja dan keandalannya di aplikasi nyata. Tanpa skema pengadaan yang mendukung penggunaan teknologi dalam negeri, validasi teknologi dan pembelajaran produksi dalam skala terbatas menjadi terhambat. Hal ini menurunkan kepercayaan industri dan investor terhadap kelayakan komersial produk semikonduktor lokal. Ketiadaan pilot project yang dikaitkan dengan pengadaan publik membuat riset nasional sulit naik kelas dari prototipe ke implementasi dan memperlambat pertumbuhan ekosistem industri semikonduktor domestik.',
    'created_at' => '2025-12-07 21:44:43',
    'updated_at' => '2025-12-07 21:44:43',
  ),
  61 => 
  array (
    'id' => 62,
    'category_id' => 6,
    'order_number' => 7,
    'full_number' => '6.7',
    'title' => 'Ketiadaan Pusat Riset Semikonduktor Berkelas Dunia',
    'description' => 'Indonesia belum memiliki pusat riset semikonduktor yang diakui setara dengan lembaga papan atas dunia, baik dari sisi fasilitas, kualitas SDM, maupun jejaring kolaborasi internasional. Laboratorium yang ada umumnya terpisah, berskala terbatas, dan belum dilengkapi peralatan canggih yang diperlukan untuk riset frontier. Kolaborasi dengan industri global dan universitas top dunia masih sporadis dan belum terikat dalam program jangka panjang yang jelas. Akibatnya, inovasi teknologi semikonduktor domestik masih bergantung pada transfer teknologi dan kerja sama luar negeri, bukan pada kepemimpinan riset lokal. Ketiadaan pusat unggulan ini juga menyulitkan Indonesia menjadi magnet bagi talenta global dan mengurangi daya tarik untuk investasi riset berskala besar di sektor semikonduktor.',
    'created_at' => '2025-12-07 21:45:29',
    'updated_at' => '2025-12-07 21:45:29',
  ),
  62 => 
  array (
    'id' => 63,
    'category_id' => 6,
    'order_number' => 8,
    'full_number' => '6.8',
    'title' => 'Kurangnya Talenta AI dan Semikonduktor dengan Reputasi Global',
    'description' => 'Jumlah peneliti dan engineer berpengalaman di bidang AI dan semikonduktor di Indonesia masih sangat terbatas, terlebih yang memiliki rekam jejak publikasi dan kolaborasi internasional bereputasi tinggi. Program pengembangan karier peneliti, kesempatan postdoc, dan visiting scholar ke pusat-pusat riset dunia belum terstruktur kuat. Selain itu, talent pipeline nasional yang menghubungkan pendidikan tinggi, pusat riset, dan industri belum terbentuk, sehingga banyak lulusan potensial beralih ke sektor lain. Kondisi ini memperlambat lahirnya pemimpin ilmiah yang mampu menarik kolaborasi global dan memimpin konsorsium riset besar. Tanpa strategi agresif pengembangan dan retensi talenta, ekosistem AI dan semikonduktor nasional akan kesulitan mencapai keunggulan kompetitif di tingkat internasional.',
    'created_at' => '2025-12-07 21:48:40',
    'updated_at' => '2025-12-07 21:48:40',
  ),
  63 => 
  array (
    'id' => 64,
    'category_id' => 6,
    'order_number' => 9,
    'full_number' => '6.9',
    'title' => 'Rendahnya Pengakuan Internasional terhadap Capaian Peneliti Indonesia',
    'description' => 'Hingga saat ini, belum ada peneliti Indonesia di bidang AI dan semikonduktor yang memperoleh penghargaan ilmiah internasional bergengsi, seperti Turing Award atau pengakuan serupa. Ketiadaan capaian di tingkat tersebut mencerminkan masih lemahnya dukungan sistemik terhadap riset berkelas dunia, mulai dari pendanaan, infrastruktur, hingga budaya kolaborasi dan kompetisi ilmiah. Mekanisme apresiasi nasional pun belum cukup mendorong peneliti untuk mengejar standar global tertinggi. Akibatnya, visibilitas ilmiah Indonesia di komunitas internasional rendah, sehingga kesempatan memimpin agenda riset global menjadi terbatas. Tanpa penguatan ekosistem yang mendorong pencapaian terobosan ilmiah, pengakuan internasional terhadap peneliti Indonesia akan tetap minim dan mengurangi daya tarik ekosistem riset nasional.',
    'created_at' => '2025-12-07 21:48:56',
    'updated_at' => '2025-12-07 21:48:56',
  ),
  64 => 
  array (
    'id' => 65,
    'category_id' => 6,
    'order_number' => 10,
    'full_number' => '6.10',
    'title' => 'Belum Kompetitifnya Perguruan Tinggi Indonesia di Peringkat Global AI dan Semikonduktor',
    'description' => 'Tidak ada perguruan tinggi atau lembaga riset Indonesia yang masuk dalam 100 besar peringkat global di bidang AI dan semikonduktor menurut pemeringkatan internasional seperti THE atau QS. Hal ini menunjukkan bahwa kualitas publikasi, kolaborasi internasional, dampak sitasi, serta output inovasi dan paten masih tertinggal dibanding institusi global terkemuka. Investasi untuk penguatan grup riset unggulan, pembaruan kurikulum, dan pembangunan jejaring internasional belum dilakukan secara konsisten dan terfokus. Selain itu, beban administratif dan insentif karier akademik sering kali tidak sejalan dengan target riset berkelas dunia. Tanpa strategi peningkatan daya saing yang terukur, posisi Indonesia dalam peta pendidikan dan riset global di bidang teknologi maju akan sulit terdongkrak.',
    'created_at' => '2025-12-07 21:49:12',
    'updated_at' => '2025-12-07 21:49:12',
  ),
  65 => 
  array (
    'id' => 66,
    'category_id' => 6,
    'order_number' => 11,
    'full_number' => '6.11',
    'title' => 'Lainnya Seputar AI & Semikonduktor',
    'description' => NULL,
    'created_at' => '2025-12-07 21:49:19',
    'updated_at' => '2025-12-07 21:49:19',
  ),
  66 => 
  array (
    'id' => 67,
    'category_id' => 7,
    'order_number' => 1,
    'full_number' => '7.1',
    'title' => 'Keterbatasan Fasilitas Terintegrasi dari Hulu ke Hilir dalam Manufaktur dan Material Maju',
    'description' => 'Fasilitas penelitian dan pengembangan manufaktur serta material maju di Indonesia masih terfragmentasi dan belum terhubung secara utuh dari hulu ke hilir. Laboratorium berkelas nano dan vakum seperti TEM/SEM/XPS, wafer slicing, coating, vacuum system, hingga fasilitas bioprocess jumlahnya terbatas, tersebar, dan sering kali berdiri sendiri tanpa alur proses yang terintegrasi. Ketiadaan pilot line terintegrasi membuat banyak teknologi berhenti pada level riset (TRL) tanpa berlanjut ke tahap kesiapan investasi (IRL) maupun industrial. Peneliti dan pelaku industri kesulitan melakukan uji proses berulang, optimasi biaya, dan validasi kualitas dalam skala quasi-komersial. Kondisi ini menghambat lahirnya prototipe yang siap diadopsi industri dan melemahkan daya saing rantai pasok material maju domestik dibanding negara lain yang telah memiliki ekosistem fasilitas terintegrasi.',
    'created_at' => '2025-12-07 22:34:27',
    'updated_at' => '2025-12-07 22:34:27',
  ),
  67 => 
  array (
    'id' => 68,
    'category_id' => 7,
    'order_number' => 2,
    'full_number' => '7.2',
    'title' => 'Bottleneck Scale-Up dari Laboratorium ke Pilot dan Industri',
    'description' => 'Proses scale-up teknologi manufaktur dan material maju dari skala laboratorium menuju pilot plant hingga industri masih menghadapi banyak bottleneck. Rekayasa proses belum mendapat porsi perhatian dan pendanaan yang memadai, sehingga optimasi parameter produksi, reliabilitas peralatan, dan konsistensi mutu produk tidak teruji dalam skala menengah. Ketiadaan pendanaan risiko dan demo plant untuk MG-Si/wafer, material baterai dan solar, serbuk additive manufacturing (AM), serta biomaterial membuat teknologi berhenti di TRL tinggi namun gagal menembus investment readiness level (IRL) dan manufacturing readiness level (MRL). Industri ragu mengambil alih teknologi yang belum terbukti robust secara operasional dan ekonomis. Tanpa jembatan scale-up yang jelas, waktu komersialisasi memanjang dan peluang pasar strategis berpotensi diambil pemain luar negeri.',
    'created_at' => '2025-12-07 22:35:29',
    'updated_at' => '2025-12-07 22:35:29',
  ),
  68 => 
  array (
    'id' => 69,
    'category_id' => 7,
    'order_number' => 3,
    'full_number' => '7.3',
    'title' => 'Kesenjangan SDM Teknis dan Ancaman Brain Drain di Sektor Material Maju',
    'description' => 'Ekosistem manufaktur dan material maju di Indonesia menghadapi kesenjangan serius dalam ketersediaan sumber daya manusia teknis, baik dari sisi jumlah maupun kompetensi. Engineer proses dengan keahlian khusus seperti nano safety, teknologi vakum, desain untuk additive manufacturing, metrologi presisi, hingga analisis siklus hidup (LCA) dan quality assurance (QA) masih sangat terbatas dan tersebar di sedikit institusi. Kurikulum pendidikan dan program sertifikasi belum seragam, sehingga standar kompetensi nasional belum terbentuk kuat. Di saat yang sama, talenta terbaik cenderung tertarik bekerja di luar negeri atau sektor non-manufaktur yang menawarkan imbalan dan lingkungan kerja lebih menarik. Tanpa strategi pengembangan dan retensi SDM yang sistematis, agenda kemandirian teknologi material maju akan sulit terwujud secara berkelanjutan.',
    'created_at' => '2025-12-07 22:35:53',
    'updated_at' => '2025-12-07 22:35:53',
  ),
  69 => 
  array (
    'id' => 70,
    'category_id' => 7,
    'order_number' => 4,
    'full_number' => '7.4',
    'title' => 'Ketergantungan Impor Bahan Baku, Mesin, dan Prekursor Kritis Material Maju',
    'description' => 'Rantai pasok manufaktur dan material maju nasional masih sangat bergantung pada impor berbagai komponen kunci, mulai dari bahan baku hingga peralatan produksi. Polysilicon dan wafer, gas dan material vakum spesial, printer dan serbuk additive manufacturing, prekursor nano, serta bio-polimer unggulan sebagian besar masih didatangkan dari luar negeri. Ketergantungan ini menyebabkan biaya produksi tinggi, lead time panjang, dan risiko gangguan suplai ketika terjadi gejolak geopolitik atau pembatasan ekspor. Upaya substitusi impor dan penguatan industri hulu domestik masih terbatas pada inisiatif sporadis tanpa roadmap terpadu. Tanpa strategi pengembangan kapasitas produksi lokal dan kemitraan teknologi yang agresif, Indonesia akan tetap rentan dalam mengamankan pasokan material kritis untuk kebutuhan industri strategis.',
    'created_at' => '2025-12-07 22:36:50',
    'updated_at' => '2025-12-07 22:36:50',
  ),
  70 => 
  array (
    'id' => 71,
    'category_id' => 7,
    'order_number' => 5,
    'full_number' => '7.5',
    'title' => 'Fragmentasi Regulasi, Standar, dan Sertifikasi Produk Material Maju',
    'description' => 'Kerangka regulasi, standar, dan sertifikasi untuk produk manufaktur dan material maju di Indonesia masih belum lengkap dan terintegrasi. Standar Nasional Indonesia (SNI) dan regulasi terkait additive manufacturing, toksisitas material nano, biocompatibility biomaterial, serta material untuk energi baru dan terbarukan masih berkembang parsial dan belum sepenuhnya selaras dengan praktik global. Ketiadaan panduan teknis yang jelas menghambat proses sertifikasi produk baru dan menimbulkan ketidakpastian bagi industri. Di sisi lain, skema preferensi produk dalam negeri belum secara sistematis mengaitkan kewajiban standar dengan insentif pasar, sehingga pelaku usaha kurang terdorong berinvestasi pada pemenuhan standar tinggi. Fragmentasi ini memperlambat adopsi material maju lokal dalam proyek pemerintah maupun pasar komersial dan mengurangi daya saing produk nasional.',
    'created_at' => '2025-12-07 22:37:07',
    'updated_at' => '2025-12-07 22:37:07',
  ),
  71 => 
  array (
    'id' => 72,
    'category_id' => 7,
    'order_number' => 6,
    'full_number' => '7.6',
    'title' => 'Ekosistem Inovasi dan Industri Material Maju yang Belum Terpadu',
    'description' => 'Ekosistem inovasi manufaktur dan material maju belum terbangun secara padu antara BUMN, swasta, universitas, dan lembaga riset. Kemitraan strategis jangka panjang untuk pengembangan produk, co-development teknologi, dan pengujian bersama masih jarang terjadi. Mekanisme joint procurement dan demand aggregation untuk menciptakan skala pasar awal produk baru belum terbentuk, sehingga banyak inovasi kesulitan menemukan pembeli pertama. Skema lisensi, valuasi kekayaan intelektual, dan pendanaan “valley of death” yang menjembatani tahap prototipe ke komersial juga belum sistemik. Akibatnya, teknologi yang lahir di laboratorium sering berhenti pada publikasi atau purwarupa skala kecil tanpa kelanjutan industri. Tanpa ekosistem inovasi yang terorkestrasi, potensi material maju lokal untuk mengisi kebutuhan sektor strategis akan tetap terfragmentasi.',
    'created_at' => '2025-12-07 22:41:03',
    'updated_at' => '2025-12-07 22:41:03',
  ),
  72 => 
  array (
    'id' => 73,
    'category_id' => 7,
    'order_number' => 7,
    'full_number' => '7.7',
    'title' => 'Lambatnya Adopsi Pasar dan Daya Saing Harga-Mutu Produk Material Maju Domestik',
    'description' => 'Produk manufaktur dan material maju dalam negeri menghadapi tantangan besar untuk bersaing dengan produk impor yang sudah mapan. Total cost of ownership (TCO) masih tinggi karena skala produksi kecil, efisiensi proses belum optimal, dan rantai pasok bahan baku belum matang. Konsistensi kualitas produk lokal kerap berfluktuasi, sementara buyer power pemasok luar negeri yang menawarkan harga agresif dan reputasi terbentuk membuat pengguna enggan beralih. Skema insentif fiskal, preferensi belanja pemerintah, serta performance warranty untuk menurunkan risiko adopsi masih terbatas. Tanpa intervensi kebijakan yang terarah dan dukungan pasar awal yang kuat, target substitusi produk impor dengan produk domestik minimal 50 persen akan sulit tercapai dalam jangka menengah.',
    'created_at' => '2025-12-07 22:44:34',
    'updated_at' => '2025-12-07 22:44:34',
  ),
  73 => 
  array (
    'id' => 74,
    'category_id' => 7,
    'order_number' => 8,
    'full_number' => '7.8',
    'title' => 'Risiko Rantai Pasok dan Lemahnya Traceability Material Kritis',
    'description' => 'Rantai pasok material kritis untuk industri energi, nano, dan bio di Indonesia menghadapi risiko tinggi karena lemahnya sistem kendali dan penelusuran asal-usul. Pengendalian kemurnian bahan, konsistensi batch produksi, serta informasi asal bahan baku dan limbah belum terdokumentasi dengan baik di sepanjang rantai nilai. Skema traceability yang andal, termasuk pelabelan, pencatatan digital, dan audit berkala, belum menjadi praktik standar. Selain itu, mekanisme recycling dan second-life untuk material energi seperti baterai dan modul surya masih minim, sehingga potensi pemanfaatan kembali dan pengurangan limbah berbahaya tidak optimal. Tanpa penguatan traceability dan manajemen siklus hidup material, risiko kualitas, keamanan, dan keberlanjutan lingkungan akan terus membayangi pengembangan industri material maju nasional.',
    'created_at' => '2025-12-07 22:44:48',
    'updated_at' => '2025-12-07 22:44:48',
  ),
  74 => 
  array (
    'id' => 75,
    'category_id' => 7,
    'order_number' => 9,
    'full_number' => '7.9',
    'title' => 'Belum Terbuktinya Kinerja Lingkungan dan Keselamatan Proses Material Maju',
    'description' => 'Kinerja lingkungan dan keselamatan proses pada rantai produksi material maju di Indonesia belum sepenuhnya terukur dan terbukti secara transparan. Jejak energi dan intensitas emisi dari proses silicon, sistem vakum, serta berbagai tahapan produksi berteknologi tinggi belum banyak dikaji melalui life cycle assessment (LCA) yang komprehensif. Limbah printing dari additive manufacturing, residu bahan kimia, serta risiko paparan nano dan biomaterial terhadap pekerja dan lingkungan belum dikelola dengan pendekatan environment, health, and safety (EHS) yang kuat. Ketiadaan sistem pemantauan nasional dan basis data risiko membuat pengambil kebijakan dan industri kesulitan merancang intervensi yang tepat. Tanpa pembuktian kinerja lingkungan dan keselamatan yang memadai, penerimaan pasar dan legitimasi sosial terhadap industri material maju dapat terganggu.',
    'created_at' => '2025-12-07 22:45:01',
    'updated_at' => '2025-12-07 22:45:01',
  ),
  75 => 
  array (
    'id' => 76,
    'category_id' => 7,
    'order_number' => 10,
    'full_number' => '7.10',
    'title' => 'Kekosongan Tata Kelola Data dan Orkestrasi Eksekusi Roadmap Material Maju',
    'description' => 'Pengembangan manufaktur dan material maju nasional belum ditopang tata kelola data dan mekanisme orkestrasi yang kuat. Belum terdapat single source of truth yang memuat peta fasilitas, kapasitas SDM, kebutuhan industri, serta status TRL, IRL, dan MRL untuk berbagai teknologi prioritas. Data tersebar di banyak lembaga tanpa format baku, sehingga sulit digunakan untuk perencanaan bersama dan pengambilan keputusan strategis. Koordinasi lintas kementerian, lembaga, dan pemerintah daerah belum diikat oleh program management office (PMO) yang memiliki mandat jelas, indikator kinerja, dan dashboard pemantauan terintegrasi. Akibatnya, eksekusi roadmap sering berjalan parsial, tumpang tindih, atau tertunda. Tanpa tata kelola data dan orkestrasi yang kuat, upaya konsolidasi program dan sumber daya untuk material maju akan sulit mencapai dampak sistemik.',
    'created_at' => '2025-12-07 22:45:18',
    'updated_at' => '2025-12-07 22:45:18',
  ),
  76 => 
  array (
    'id' => 77,
    'category_id' => 7,
    'order_number' => 11,
    'full_number' => '7.11',
    'title' => 'Lainnya Seputar Manufaktur & Material Maju',
    'description' => NULL,
    'created_at' => '2025-12-07 22:45:36',
    'updated_at' => '2025-12-07 22:45:36',
  ),
  77 => 
  array (
    'id' => 78,
    'category_id' => 8,
    'order_number' => 1,
    'full_number' => '8.1',
    'title' => 'Ketergantungan Teknologi dan Bahan Baku Impor Menghambat Kemandirian Industri',
    'description' => 'Ketergantungan industri petrokimia, baterai, dan katalis pada teknologi asing serta bahan baku impor seperti LPG, naphtha, kondensat, dan logam katalis membuat kemandirian industri sulit terwujud. Struktur industri lebih banyak berperan sebagai perakit dan pengolah sederhana, bukan sebagai pemilik teknologi proses dan formulasi produk bernilai tambah tinggi. Ketergantungan ini memperlemah posisi tawar terhadap pemasok global dan menambah kerentanan ketika terjadi gejolak harga atau gangguan pasokan. Di sisi lain, riset universitas yang berpotensi mensubstitusi teknologi impor sulit masuk ke rantai produksi karena kesenjangan standar teknis, kurangnya mekanisme alih teknologi, dan minimnya fasilitas uji berskala industri. Tanpa terobosan di sisi teknologi proses dan bahan baku hulu, agenda hilirisasi hanya akan memperdalam ketergantungan, bukan mendorong kedaulatan industri nasional.',
    'created_at' => '2025-12-07 22:46:27',
    'updated_at' => '2025-12-07 22:46:27',
  ),
  78 => 
  array (
    'id' => 79,
    'category_id' => 8,
    'order_number' => 2,
    'full_number' => '8.2',
    'title' => 'Fragmentasi Regulasi Menyebabkan Ketidakpastian dan Tingginya Risiko Industri',
    'description' => 'Kerangka regulasi dan kebijakan hilirisasi di Indonesia masih terfragmentasi lintas sektor, dengan aturan yang kerap tumpang tindih, tidak fleksibel, dan sulit dieksekusi secara konsisten. Orkestrasi data, standar, dan kewenangan antar kementerian/lembaga belum terbangun, sehingga pelaku industri menghadapi ketidakpastian tinggi saat mengembangkan investasi baru atau bermitra dengan perguruan tinggi. Dalam kondisi regulasi yang belum sinkron, industri cenderung menghindari risiko kolaborasi teknologi domestik dan memilih teknologi impor yang sudah teruji. Akibatnya, banyak riset berhenti di tahap prototipe tanpa pernah masuk ke rantai produksi. Produk inovasi lokal gagal menembus pasar hilir, dan berbagai skema insentif riset tidak menghasilkan dampak ekonomi yang signifikan. Tanpa penyederhanaan dan harmonisasi regulasi, risiko kegagalan hilirisasi akan terus berulang.',
    'created_at' => '2025-12-07 22:46:40',
    'updated_at' => '2025-12-07 22:46:40',
  ),
  79 => 
  array (
    'id' => 80,
    'category_id' => 8,
    'order_number' => 3,
    'full_number' => '8.3',
    'title' => 'Rendahnya Standardisasi dan Validasi Produk Riset Memicu Trust Gap dengan Industri',
    'description' => 'Industri petrokimia, katalis, dan baterai membutuhkan produk dengan spesifikasi terukur, konsisten, dan terverifikasi secara independen, sementara fasilitas uji setara industri di perguruan tinggi masih terbatas. Banyak penelitian berulang pada topik yang sama dan berhenti di tingkat kesiapan teknologi menengah (TRL 4–6) tanpa kelanjutan pengembangan menuju validasi skala pilot. Ketiadaan standar nasional Indonesia (SNI) dan skema sertifikasi yang jelas untuk produk baru menimbulkan kesenjangan kepercayaan antara akademisi dan pelaku usaha. Industri ragu mengadopsi teknologi yang belum dibuktikan performa dan reliabilitasnya di lingkungan operasi nyata. Konsekuensinya, program pendanaan kolaboratif seperti Kedaireka cenderung menghasilkan proyek kecil yang dampak ekonominya lokal dan terbatas. Tanpa ekosistem standardisasi dan validasi yang kuat, riset sulit naik kelas menjadi solusi industri.',
    'created_at' => '2025-12-07 22:46:52',
    'updated_at' => '2025-12-07 22:46:52',
  ),
  80 => 
  array (
    'id' => 81,
    'category_id' => 8,
    'order_number' => 4,
    'full_number' => '8.4',
    'title' => 'Ketiadaan Data Terpadu dan Benchmark Global Melemahkan Presisi Kebijakan Hilirisasi',
    'description' => 'Perumusan kebijakan hilirisasi di Indonesia masih kekurangan data terpadu yang menggambarkan keterkaitan antara riset, industri, dan rantai pasok secara utuh. Tidak tersedia national dashboard yang memetakan kapasitas produksi, kebutuhan bahan baku, portofolio riset, serta peluang pasar seperti yang dikembangkan negara pesaing. Data tersebar dalam silo antar kementerian dan lembaga, tanpa integrasi dan benchmark terhadap praktik global. Akibatnya, roadmap hilirisasi cenderung bersifat administratif, tidak adaptif terhadap dinamika pasar, dan sulit diukur capaian nyatanya. Ketiadaan indikator kinerja berbasis data membuat prioritas program sering berubah-ubah dan menghambat konsistensi investasi. Tanpa fondasi data yang kuat dan sistem pemantauan yang transparan, kebijakan hilirisasi berisiko tidak tepat sasaran dan gagal menciptakan nilai tambah maksimal.',
    'created_at' => '2025-12-07 22:47:05',
    'updated_at' => '2025-12-07 22:47:05',
  ),
  81 => 
  array (
    'id' => 82,
    'category_id' => 8,
    'order_number' => 5,
    'full_number' => '8.5',
    'title' => 'Transformasi Digital dan AI Belum Dimanfaatkan sebagai Enabler Hilirisasi',
    'description' => 'Transformasi digital dan kecerdasan artifisial (AI) belum dimanfaatkan sebagai enabler utama dalam percepatan hilirisasi. Padahal, AI berpotensi besar digunakan untuk memetakan portofolio riset, status TRL, peluang pasar, dan kesesuaian teknologi dengan kebutuhan industri secara dinamis. Ketiadaan sistem nasional berbasis AI yang mengintegrasikan data riset, industri, dan rantai pasok menyebabkan banyak potensi riset unggul, misalnya di bidang katalis atau baterai, tidak terdeteksi dan tidak terhubung dengan mitra industri yang tepat. Peluang kolaborasi hilang, pendanaan tidak tepat sasaran, dan keputusan investasi menjadi reaktif. Tanpa platform cerdas yang mampu mengorkestrasi informasi lintas sektor, proses matching antara inovasi dan kebutuhan pasar akan tetap manual, lambat, dan bergantung pada jejaring informal, sehingga percepatan hilirisasi tertunda.',
    'created_at' => '2025-12-07 22:47:20',
    'updated_at' => '2025-12-07 22:47:20',
  ),
  82 => 
  array (
    'id' => 83,
    'category_id' => 8,
    'order_number' => 6,
    'full_number' => '8.6',
    'title' => 'Beban Pajak dan Perizinan Kompleks Menghambat Investasi Pabrik Terintegrasi',
    'description' => 'Investasi pembangunan pabrik terintegrasi dari hulu ke hilir sering tertunda akibat beban pajak dan kompleksitas perizinan yang tinggi. Pengenaan PPN atas peralatan pabrik, prosedur perizinan berlapis, serta ketiadaan jalur fast track bagi proyek strategis nasional menambah biaya dan waktu realisasi investasi. Investor harus menanggung risiko regulasi yang besar sebelum fasilitas beroperasi, sehingga daya tarik Indonesia kalah dibanding negara tetangga yang menawarkan proses izin lebih cepat dan insentif fiskal lebih kompetitif. Kondisi ini melemahkan upaya membangun klaster industri hilir yang terintegrasi dengan sumber daya alam domestik. Tanpa reformasi perpajakan investasi dan simplifikasi perizinan, banyak peluang pembangunan pabrik bernilai tambah tinggi akan berpindah ke yurisdiksi lain, mengurangi potensi penciptaan lapangan kerja dan devisa.',
    'created_at' => '2025-12-07 22:47:31',
    'updated_at' => '2025-12-07 22:47:31',
  ),
  83 => 
  array (
    'id' => 84,
    'category_id' => 8,
    'order_number' => 7,
    'full_number' => '8.7',
    'title' => 'Ketidaksinkronan Ekspor–Impor Menyebabkan Inefisiensi Pasar Domestik',
    'description' => 'Kebijakan ekspor–impor di sektor hilirisasi belum terharmonisasi, sehingga menimbulkan berbagai inefisiensi di pasar domestik. Kasus di mana produsen dalam negeri mengekspor produk bernilai tambah, sementara BUMN lain secara paralel mengimpor produk serupa, menunjukkan lemahnya koordinasi rantai pasok nasional. Pola serupa juga terjadi pada bahan farmasi dan mineral, memicu situasi oversupply di satu sisi dan kekosongan pasokan di sisi lain. Ketidaksinkronan ini menghilangkan peluang substitusi impor dan penguatan pasar domestik bagi produk lokal. Pelaku industri kesulitan merancang strategi investasi jangka panjang karena tidak ada sinyal kebijakan yang konsisten. Tanpa penyelarasan kebijakan ekspor–impor berbasis peta neraca komoditas, efisiensi penggunaan kapasitas nasional dan kedaulatan industri sulit tercapai.',
    'created_at' => '2025-12-07 22:47:51',
    'updated_at' => '2025-12-07 22:47:51',
  ),
  84 => 
  array (
    'id' => 85,
    'category_id' => 8,
    'order_number' => 8,
    'full_number' => '8.8',
    'title' => 'Kesenjangan SDM dan Kapasitas Riset Terintegrasi Menahan Laju Hilirisasi',
    'description' => 'Hilirisasi terhambat oleh kesenjangan sumber daya manusia riset, proses, dan rekayasa yang belum terkonsolidasi lintas lembaga. Kapasitas insinyur proses, teknolog industri, dan manajer proyek yang mampu menjembatani laboratorium dan pabrik masih terbatas. Kolaborasi perguruan tinggi dan industri umumnya bersifat sporadis, berbasis proyek jangka pendek, tanpa sistem pembelajaran kolektif dan kurikulum bersama. Akibatnya, banyak inovasi membutuhkan waktu lama untuk di-scale up karena kurangnya tim multidisiplin yang solid. Time-to-market produk lokal menjadi panjang, sehingga peluang pasar sering terlewat atau diambil pemain asing. Tanpa investasi serius pada pengembangan kompetensi terintegrasi dan mekanisme mobilitas talenta lintas sektor, agenda hilirisasi akan terus tertahan pada tahap uji coba.',
    'created_at' => '2025-12-07 22:48:04',
    'updated_at' => '2025-12-07 22:48:04',
  ),
  85 => 
  array (
    'id' => 86,
    'category_id' => 8,
    'order_number' => 9,
    'full_number' => '8.9',
    'title' => 'Ketiadaan Konsorsium Nasional Membuat Ekosistem Hilirisasi Terfragmentasi',
    'description' => 'Ekosistem hilirisasi di Indonesia masih terfragmentasi karena belum terbentuknya koordinasi kebijakan lintas sektor dan konsorsium nasional yang kuat. Hilirisasi belum dikelola sebagai satu ekosistem nilai yang menghubungkan riset, industri, dan investasi dalam kerangka agenda bersama. Tidak ada national consortium yang secara formal mengikat kampus, industri, dan regulator untuk berbagi risiko, data, dan manfaat. Ketiadaan regulatory sandbox, fasilitas pendanaan khusus hilirisasi, dan kebijakan berbasis data serta AI membuat eksperimen model bisnis dan teknologi berjalan lambat. Program antar kementerian sering berjalan sendiri-sendiri tanpa orkestrasi. Tanpa pembentukan konsorsium riset–industri dan mekanisme koordinasi yang jelas, berbagai inisiatif hilirisasi akan tetap berskala kecil, terpisah, dan sulit menghasilkan lompatan daya saing industrial nasional.',
    'created_at' => '2025-12-07 22:48:19',
    'updated_at' => '2025-12-07 22:48:19',
  ),
  86 => 
  array (
    'id' => 87,
    'category_id' => 8,
    'order_number' => 10,
    'full_number' => '8.10',
    'title' => 'Lainnya Seputar Hilirisasi & Industrialisasi',
    'description' => NULL,
    'created_at' => '2025-12-07 22:49:04',
    'updated_at' => '2025-12-07 22:49:04',
  ),
);
